monero-project/monero-site

- knowledge-base/moneropedia/transaction.md
The in-depth information text was scavenged from a fluffypony’s post in the forum.
> Add more information in the transaction section of moneropedia.

- knowledge-base/developer-guides/wallet-rpc.md
get_bulk_payments accepts "payment_ids", otherwise returns all transactions from min_block_height.
> typo fix and changed payment_id to payment_ids

- .gitignore
- README.md
- _config.yml
- _plugins/jekyll-live-tiles.rb
- _plugins/plugin.rb
- _plugins/sitemap_generator.rb
Site is now compatible with Jekyll 3+ . The plugins had a lot that wasn't compatible anymore so I updated the jekyll-live-titles and sitemap_generator plugins with the latest version I found on their respective repos. I noticed that there were some customizations made in the history on live tiles, so I can go back and try and add/fix anything if I overwrote something.
> Jekyll3 upgrade

- _data/merchants.yml
Related blog post: http://blog.coincut.com/2016/08/17/buy-dash-ethereum-monero-gbp-wallets
> CoinCut service - Buying Monero with fiat (GBP)

- _includes/header.html
- _strings_en.yml
- blog/index.html
- getting-started/contribute.md
- getting-started/index.md
The numeric pagination on the blog page leads to `https://getmonero.org/blog/page3/blog/page4/404` etc now, this has been fixed.
I saw all the views and answers this question got on Stack Exchange: http://monero.stackexchange.com/questions/1647/for-newcomers-to-the-monero-community-what-can-we-do-to-help-the-project
I was not able to find any place on the Monero website where this was explained so I made a page. I'm also a newcomer so please add or edit the content if needed. The content is mostly based on the answers to the question on Stack Exchange.
> Fix blog pagination and add contribute page

- knowledge-base/openalias.md
It looks like the formatter for the website doesn't make raw links clickable (like usual markdown formatters).
Making this an explicit link hopefully helps (it works this way on other pages).
Also use `https` instead of `http` (there is already a redirect in place).
> make the link clickable

- downloads/index.md
Despite the obviousness of the length of the hash, and the fact that
there is a small note on the page noting the type of hash, the point
should be made clearly and quickly.
> Downloads: clarify that checksum is SHA256

- knowledge-base/user-guides/view_only.md
I noticed the instructions on how to create view-only wallets were kind of outdated, so I completely rewrote them. I've tested this on both Mac and Ubuntu, I assume it's working on Windows as well?
I wasn't sure about the `title`, `title-kick` etc, so I just removed them for now...
> Rewrite View Only Wallet user guide

- _data/merchants.yml
Living Room of Satoshi, allows payment of any bill or bank account in Australia with Bitcoin. The URL in the pull request includes a parameter that takes you directly to the monero payment option.
> Add Living Room of Satoshi to Merchants page

- _data/merchants.yml
MoneroWorld no longer hosts an explorer, but two other are now maintained based off the same onion explorer source.
> rm MoneroWorld explorer and add two others

- _data/merchants.yml
I've deprecated `pymonero` and have began merging the functionality of it into `MoneroPy`, which is actively maintained and undergoing development. `pymonero` therefore should not be listed anymore.
> Update python package - pymonero to MoneroPy

- README.md
Static content is now available in GitHub, but in a different repo.
@fluffypony mentioned in issue #247
> Updating README info on static content repo.

- _includes/header.html
- _strings_en.yml
Currently, the link is inside the "Contributing To Monero" page, but that isn't very easily accessible. So I added it to the menus.
I'd even argue that maybe it should be a section on the homepage instead. Let me if there is a better place for it then the menu where I put it.
> Add link to GitHub from menu

- community/hangouts/index.md
The other links will automatically re-center themselves.
Screenshot:
> Removing broken link to rocket.xmrnation.com

- css/custom.css
The @font-face declaration has an erroneous `sans-serif` which prevents the font from being displayed (if you don't have the font installed locally).
> Fix 'Open Sans' @font-face declaration

- css/custom.css
Fixes #324.
`1rem` will normally convert to `16px`, but it's a relative unit that is based on the font size of `<html>`. If the user's browser overrides the default font size, it'll change the value of `1rem` and affect how the icons are taken from the spritesheet. Switching to `px` when using `background-position` will prevent this.
> Use absolute units with background-position

- _posts/2016-03-05-overview-and-logs-for-the-dev-meeting-held-on-2016-03-05.md
closes #111 
If anyone still has the logs, it'd be great if we could add them, but it's better to have the post and no logs than to have no post IMO.
> Create missing Dev Meeting Post for Posterity (2016-03-05)

- Gemfile
Source: Jekyll complaining at me
```
Please add the following to your Gemfile to avoid polling for changes:
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
```
> Add wdm gem on Windows

- resources/developer-guides/daemon-rpc.md
- resources/developer-guides/wallet-rpc.md
- resources/moneropedia/account.md
- resources/moneropedia/base64-address.md
- resources/moneropedia/jump-service.md
- resources/moneropedia/subscription.md
This PR includes the following:
- Fix issue with daemon-rpc example styling.
- Remove references to deprecated class “cli-code” and replace with
code blocks where necessary.
- Add new line between all RPC calls and outputs.
- Use 3-apostrophe code blocks instead of indent for all curl examples
for markdown neatness and to enable future syntax highlighting.
> Improve Developer Guides layout & code blocks

- _data/tags.yml
The tag `protocol upgrade` was first used in this [blog post](https://getmonero.org/2017/09/13/september-15-2017-protocol-upgrade-hard-fork.html), but never added to the tag list.
> Add missing protocol upgrade tag

- css/custom.css
Currently the merchants URLs are black which is different from all other URLs. This PR changes them to orange as well.
edit: I'm not sure if it's intended to be black.
> Fix merchants URL color

- README.md
Maybe a link to the website on top of the Github repository would be nice too.
> Add links to getmonero.org in README.md

- resources/developer-guides/daemon-rpc.md
The links were partially fixed recently in https://github.com/monero-project/monero-site/pull/402 but these 3 links were forgotten.
> Fix remaining broken links in RPC documentation

- css/custom.css
Fix the large MyMonero logo on downloads page. The default width shouldn't be set to 100% of the page width.
> Fix image width

- _data/merchants.yml
Fix #449 
Site was previously removed because it didn't mention Monero as a payment method, but is [added now](https://koddos.net/payment-methods.html).
> Add KoDDoS.net to merchants.yml

- _data/merchants.yml
Tuxcon accepts Monero as payment for web and mail hosting services
> Added in Tuxcon web + mail hosting

- resources/developer-guides/daemon-rpc.md
Describe return fields of RPC call 'sendrawtransaction' in daemon-rpc guide
closes #224
> Add doc for sendrawtransaction in daemon-rpc guide

- blog/tags/protocol upgrade.md
Clicking on the protocol upgrade tag link on the bottom of [this blog post](https://getmonero.org/2017/09/13/september-15-2017-protocol-upgrade-hard-fork.html) results in 404.
edit: Somehow I forgot it in my last PR https://github.com/monero-project/monero-site/pull/500 as this directory was ignored by the `.gitignore` file.
> Fix missing protocol upgrade tag

- _i18n/en/resources/user-guides/securely_purchase.md
- _i18n/es/resources/user-guides/securely_purchase.md
- _i18n/template/resources/user-guides/securely_purchase.md
I think this part (`@view-only`) shouldn't be a normal text but an actual link to the page.
https://getmonero.org/resources/user-guides/securely_purchase.html
> Add a link to 'View Only Wallets' in 'Securely purchasing and storing Monero' page

- _i18n/en/resources/developer-guides/daemon-rpc.md
- _i18n/es/resources/developer-guides/daemon-rpc.md
- _i18n/template/resources/developer-guides/daemon-rpc.md
This important flag was not documented. What's worse, the default value stops tx propagation, which definitely need mentioning.
> Describe "do_not_relay" flag and the strange default

- _i18n/en/resources/developer-guides.md
- _i18n/es/resources/developer-guides.md
- _i18n/it/resources/developer-guides.md
- _i18n/template/resources/developer-guides.md
Small typo to correct in the English file (as well as the template, and other unfinished translations).
> Typo in developer-guides.md

- _includes/footer.html
- language.php
- legal/index.md
Replaced Google Analytics with an open-source, self-hosted alternative: Matomo.
Some cleanup in the footer include also.
> Replaced Google Analytics with Matomo

- _data/merchants.yml
BitMEX no longer offer an XMR contract, and previously settled their Monero contract in Bitcoin anyway.
> Remove BitMEX from merchants list

- _i18n/en/resources/moneropedia/transaction.md
- _i18n/es/resources/moneropedia/transaction.md
- _i18n/fr/resources/moneropedia/transaction.md
- _i18n/it/resources/moneropedia/transaction.md
- _i18n/template/resources/moneropedia/transaction.md
- resources/moneropedia/transaction.md
While reading moneropedia articles, i found that the Transaction article was still refering to a 'mixin_count' parameter.
I suggest to replace it with a link to \@ring-size article, and adding the ~~faxt~~ fact that it is not only the count of foreign transaction, but ~~also yours~~ all outputs.
> Moneropedia transaction mixin cleanup

- _posts/2016-03-05-overview-and-logs-for-the-dev-meeting-held-on-2016-03-05.md
- _posts/2017-09-16-logs-for-the-Community-meeting-held-on-2017-09-16.md
- _posts/2017-09-17-overview-and-logs-for-the-dev-meeting-held-on-2017-09-17.md
- _posts/2017-09-24-logs-for-the-Kovri-dev-meeting-held-on-2017-09-24.md
- _posts/2017-09-30-logs-for-the-Community-meeting-held-on-2017-09-30.md
- _posts/2017-10-01-overview-and-logs-for-the-dev-meeting-held-on-2017-10-01.md
- _posts/2017-10-06-logs-for-the-Kovri-dev-meeting-held-on-2017-10-06.md
- _posts/2017-10-14-logs-for-the-Community-meeting-held-on-2017-10-14.md
- _posts/2017-10-22-overview-and-logs-for-the-dev-meeting-held-on-2017-10-22.md
- _posts/2017-10-28-logs-for-the-Community-meeting-held-on-2017-10-28.md
- _posts/2017-10-30-logs-for-the-Monero-Research-Lab-meeting-held-on-2017-10-30.md
This solves #746
A few posts had the date hard written in the md file, when Jekyll is building automatically a date header based on the date in the title.
As a result, those posts were displaying the date twice.
I removed the hard written date.
> Correct double date in Posts

- _i18n/en/resources/developer-guides/wallet-rpc.md
- _i18n/es/resources/developer-guides/wallet-rpc.md
- _i18n/fr/resources/developer-guides/wallet-rpc.md
- _i18n/it/resources/developer-guides/wallet-rpc.md
References #694.
Includes documentation and examples for new commands dealing with subaddresses.
Updates for existing commands that now deal with subaddresses. Some fields unrelated to subaddresses were missing, and are now included.
> Update RPC documentation for commands involving subaddresses

- _posts/2018-06-23-logs-for-the-Community-meeting-held-on-2018-06-23.md
Tested on the following platforms:
Windows 10 | KO | OK | OK | OK | OK | OK
Edge is displaying the content box larger than it should.
It is because of long link `https://taiga.getmonero.org/media/attachments/5/7/4/5/7d6f57b35ee6dc6df9f74534cf9a3693a3d04741d0c97cfca2837692fcda/quickfacts_v2_g.pdf` not been split, so perhaps CSS should be corrected here. Any clue @rehrar?
Should i split the link in two to avoid this mess?
> Logs from 2018-06-23 Community meeting

- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
- _i18n/fr/resources/user-guides/securely_purchase.md
- _i18n/it.yml
- _i18n/pl.yml
- community/hangouts/index.md
- downloads/index.md
- resources/user-guides/index.md
This is a small update for fr.yml on which some sentences were missing translation since relocalization (why in hell didn't i see that before??)
This try (another time) to add the nicehash guide "How to mine Monero XMR without a mining equipement" which has always been here, but never been accessible through user-guide index page.
> Minor French Update + NiceHash guide re-re-added

- _i18n/en.yml
- _i18n/en/resources/user-guides/ledger-wallet-cli.md
- _i18n/es.yml
- _i18n/es/resources/user-guides/ledger-wallet-cli.md
- _i18n/fr.yml
- _i18n/fr/resources/user-guides/ledger-wallet-cli.md
- _i18n/it.yml
- _i18n/it/resources/user-guides/ledger-wallet-cli.md
- _i18n/pl.yml
- _i18n/pl/resources/user-guides/ledger-wallet-cli.md
- resources/user-guides/index.md
- resources/user-guides/ledger-wallet-cli.md
This is a new user-guide based on @dEBRUYNE-1 [How do I generate a Ledger Monero wallet with the CLI (monero-wallet-cli)?](https://monero.stackexchange.com/questions/8503/how-do-i-generate-a-ledger-monero-wallet-with-the-cli-monero-wallet-cli) StackExchange Q&A, as i told i'll do on [twitter](https://twitter.com/boubour_/status/1004106259937849344).
A few corrections have been applied :
+ De-personalized (s/"I"/"We"/g)
+ Download links moved to getmonero.org instead of GitHub
+ Typo Correction
- Mac OS referring to GUI 0.12.1.0 instead of CLI 0.12.2.0
- Monero v0.12.1.0 mentioned instead of v0.12.2.0
- s/cavaet/caveat/g
+ Precision on installation section of Ledger Monero app guide for windows
+ Update the "need assistance" final note to link to the StackExchange answer.
And i already …
> Ledger Wallet CLI Guide (dEBRUYNE)

- _plugins/screenshots.rb
I did notice in #735 that user-guides did not used their local png folders.
So i made this small ruby script to copy localized png files to the site directory during the build.
Working perfectly here.
Then all the localized screenshot i took to solve #729 could be used, and every user could have a localized experience up to the screenshot itself.
Up to you to test @erciccione
> Localized user-guide screenshots

- _i18n/ar/resources/moneropedia/canonically-unique-host.md
- _i18n/ar/resources/moneropedia/locally-unique-host.md
- _i18n/ar/resources/moneropedia/subscription.md
- _i18n/en/resources/moneropedia/canonically-unique-host.md
- _i18n/en/resources/moneropedia/locally-unique-host.md
- _i18n/en/resources/moneropedia/subscription.md
- _i18n/es/resources/moneropedia/canonically-unique-host.md
- _i18n/es/resources/moneropedia/locally-unique-host.md
- _i18n/es/resources/moneropedia/subscription.md
- _i18n/fr/resources/moneropedia/canonically-unique-host.md
- _i18n/fr/resources/moneropedia/locally-unique-host.md
- _i18n/fr/resources/moneropedia/subscription.md
- _i18n/it/resources/moneropedia/canonically-unique-host.md
- _i18n/it/resources/moneropedia/locally-unique-host.md
- _i18n/it/resources/moneropedia/subscription.md
- _i18n/pl/resources/moneropedia/canonically-unique-host.md
- _i18n/pl/resources/moneropedia/locally-unique-host.md
- _i18n/pl/resources/moneropedia/subscription.md
- resources/moneropedia/canonically-unique-host.md
- resources/moneropedia/locally-unique-host.md
- resources/moneropedia/subscription.md
While translating Moneropedia, i found out that the link to wikipedia `/etc/hosts` page was wrong.
The page is not under `https://en.wikipedia.org/wiki/Etc/hosts` anymore but under `https://en.wikipedia.org/wiki/Hosts_(file)`
This correct the link for all occurence of it in all moneropedia article of all languages:
- cannonicaly-unique host
- locally-unique host
- subscription
> Wikipedia link corrected in Moneropedia articles

- _i18n/es.yml
I'm not sure if there's an issue about this update/request. Hope that I'm not causing any troubles, thank you in advance guys.
As you must know, the es.yml file contains most of the content for the getmonero dot org site. There are other files that needs translation and I'll be working on them too. I experienced just one problem when testing the file: the Stack Exchange section didn't translated, which corresponds to line 104. Maybe that line depends on other file in the es folder but I'm not aware of that now. 
A minor problem is the space used when translating some of the titles in the Team page (Research Lab, which translates into Laboratorio de Investigación, actually I just put "Lab. de Investigación" but it's still too long, and Special Thanks - Agradecimientos Especiales. Those …
> Translation of es.yml

- _data/lang/ar/roadmap.yml
- _data/lang/en/roadmap.yml
- _data/lang/es/roadmap.yml
- _data/lang/fr/roadmap.yml
- _data/lang/it/roadmap.yml
- _data/lang/pl/roadmap.yml
- _data/lang/template/roadmap.yml
This solves #805
All languages needs to be reviewed (or retranslated) @erciccione.
This should not be merged before 8/1 as it states kovri alpha release is completed at this date.
Is it still the goal @anonimal?
> Roadmap update to match bulletproofs & kovri updates

- _i18n/ar/resources/moneropedia/pedersen-commitment.md
- _i18n/en/resources/moneropedia/pedersen-commitment.md
- _i18n/es/resources/moneropedia/pedersen-commitment.md
- _i18n/fr/resources/moneropedia/pedersen-commitment.md
- _i18n/it/resources/moneropedia/pedersen-commitment.md
- _i18n/pl/resources/moneropedia/pedersen-commitment.md
The Pedersen commitment Moneropedia entry was only using the "pedersen" and "commitment(s)" terms.  
I added the "pedersen-commitment(s)" variant so a link could be created not only on pedersen or commitment, but on the whole pedersen-commitment at once.
> Update Pedersen Commitment Moneropedia terms

- _i18n/ar.yml
- _i18n/de.yml
- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
- _i18n/it.yml
- _i18n/nl.yml
- _i18n/pl.yml
- _i18n/pt-br.yml
- _i18n/ru.yml
- _i18n/tr.yml
- _i18n/zh-cn.yml
- _i18n/zh-tw.yml
- library/index.md
This is necessary because the old structure is not fully compatible with Weblate, which struggle to parse it and gets confused if the order of the entries is changed. I transferred the translations for all languages to the new structure.
Some more sections will need refactoring for the same reason (IRC channel list, press-kit and probably more)
> Refactor 'Library' section to be easily parsed by Weblate

- .github/workflows/ci.yml
> When set to true, GitHub cancels all in-progress jobs if any matrix job fails. Default: true
> workflows: disable fast fail

- css/custom.css
Some languages in the dropdown menu were not clickable when the elements behind it had the same z-index. Rised the z-index of the language dropdown, so we are always sure it has priority over other elements.
Before:
After:
> Fix z-index of language dropdown

- _data/lang/ar/navigation.yml
- _data/lang/de/navigation.yml
- _data/lang/es/navigation.yml
- _data/lang/fr/navigation.yml
- _data/lang/it/navigation.yml
- _data/lang/nl/navigation.yml
- _data/lang/pl/navigation.yml
- _data/lang/pt-br/navigation.yml
- _data/lang/ru/navigation.yml
- _data/lang/tr/navigation.yml
- _data/lang/zh-cn/navigation.yml
- _data/lang/zh-tw/navigation.yml
It's an empty tab. It was removed for English, but not for the other languages.
> navigation: remove 'technical-specs' tab for all languages

- blog/index.html
The link is invalid, which causes a 404 error when people try to navigate to page 1 from any other page of the blog.
> blog: fix wrong link to page 1

- resources/developer-guides/daemon-rpc.md
- resources/developer-guides/wallet-rpc.md
Remove `-X POST` from calls to curl. It doesn't do anything good and now the commands are shorter.
[Article by curl author warning against the unnecessary use of -X](https://daniel.haxx.se/blog/2015/09/11/unnecessary-use-of-curl-x/)
> Developer Guides: Remove unnecessary curl parameters

- _i18n/ar/resources/moneropedia/address.md
- _i18n/de/resources/moneropedia/address.md
- _i18n/en/resources/moneropedia/address.md
- _i18n/es/resources/moneropedia/address.md
- _i18n/fr/resources/moneropedia/address.md
- _i18n/it/resources/moneropedia/address.md
- _i18n/nl/resources/moneropedia/address.md
- _i18n/pl/resources/moneropedia/address.md
- _i18n/pt-br/resources/moneropedia/address.md
- _i18n/ru/resources/moneropedia/address.md
- _i18n/tr/resources/moneropedia/address.md
- _i18n/zh-cn/resources/moneropedia/address.md
- _i18n/zh-tw/resources/moneropedia/address.md
- get-started/contributing/index.md
Use a subaddress for donations instead of the 4.. address.
It is the same wallet, so the publicly known view key remains valid.
Fixes #985
> update genfund donation to subaddress -- still same wallet

- index.html
This fixes video playback in Safari. 
~~Do not merge because it now requires to click on the play button in the bottom left corner to start the video in Chrome.~~
> index: fix video in Safari

- get-started/faq/index.md
in #967 i used jekyll's native way to link to a blog post: `post_url`. The prolem is that to test the website, it's usually a good idea to limit the amount of loaded blog posts to only one by using `--limit-posts 1` or the build time will basically double. If `--limit-posts 1` is used in concomitance with `post_url` the build will fail, since jekyll won't be able to find the linked blog post (unless it's the last one).
This doesn't matter from a functional point of view, but loading all blog posts while testing it's a waste of time. This PR replaces `post_url` with a simpler direct link to the blog post. This will avoid the failure of the build when using `--limit-posts`.
Sorry for the double PR, i wasn't aware of this incompatibility.
> Dont't use jekyll's 'post_url' for linking to a blog post

- _i18n/en.yml
- downloads/index.md
Added for both GUI and CLI.
Requires #1030, Closes #1028
Preview (GUI):
> Downloads: add warning about binaries being potentially flagged as malware by AVs

- _i18n/en.yml
- css/custom.css
- get-started/accepting/index.md
and add ul.logo class to general CSS.
My fear is that merchants looking at this page could think there are not info for them, since the 'Instructions for merchants' are at the bottom. The TOC will avoid the problem.
> accepting: add TOC

- netlify.toml
This configuration file is needed before we activate Netlify for building and deploying a preview of the incoming PRs (and master) on this repository.
Netlify will allow us to build and deploy incoming pull requests in this repo. A bot will post a comment in the PR with a link to the preview of the built PR. This is particularly useful for contributors who don't have a build environment for getmonero, but want to see how their changes will look like once merged. A PR gets usually built and deployed in ~3-5 minutes.
I opened a test PR in my repository which contains the revamped homepage as proposed in #948. You can take a look at my PR to see netlify at work and the preview of the new homepage built and available: https://github.com/erciccione/monero-site/pull/17
To have this working we …
> Add config file for Netlify

- _i18n/ar/resources/user-guides/node-i2p-zero.md
- _i18n/de/resources/user-guides/node-i2p-zero.md
- _i18n/en/resources/user-guides/node-i2p-zero.md
- _i18n/es/resources/user-guides/node-i2p-zero.md
- _i18n/fr/resources/user-guides/node-i2p-zero.md
- _i18n/it/resources/user-guides/node-i2p-zero.md
- _i18n/nl/resources/user-guides/node-i2p-zero.md
- _i18n/pl/resources/user-guides/node-i2p-zero.md
- _i18n/pt-br/resources/user-guides/node-i2p-zero.md
- _i18n/ru/resources/user-guides/node-i2p-zero.md
- _i18n/tr/resources/user-guides/node-i2p-zero.md
- _i18n/zh-cn/resources/user-guides/node-i2p-zero.md
- _i18n/zh-tw/resources/user-guides/node-i2p-zero.md
The original guide was updated: https://github.com/i2p-zero/i2p-zero/commit/2d40bf463c0ecbc327c1458f59e889e065bdcdde
> Update user guide 'Run a Monero node through I2P with I2P-zero'

- README.md
- _includes/head.html
The old logo showing on social medias is too large and end up being trimmed:
Twitter:
Reddit:
Replaced it with the simple Monero Logo. If a logo is specified using 'image:' in the front matter, jekyll will show this one instead. This also allow us to easily make specific meta-images for each blog post. I will add the possibility to add the image in the body of the post in a subsequent PR.
> Meta tags: Change opengraph logo and add possiblity to use custom one

- _i18n/ar/resources/user-guides/importing_blockchain.md
- _i18n/de/resources/user-guides/importing_blockchain.md
- _i18n/en/resources/user-guides/importing_blockchain.md
- _i18n/es/resources/user-guides/importing_blockchain.md
- _i18n/fr/resources/user-guides/importing_blockchain.md
- _i18n/it/resources/user-guides/importing_blockchain.md
- _i18n/nl/resources/user-guides/importing_blockchain.md
- _i18n/pl/resources/user-guides/importing_blockchain.md
- _i18n/pt-br/resources/user-guides/importing_blockchain.md
- _i18n/ru/resources/user-guides/importing_blockchain.md
- _i18n/tr/resources/user-guides/importing_blockchain.md
- _i18n/zh-cn/resources/user-guides/importing_blockchain.md
- _i18n/zh-tw/resources/user-guides/importing_blockchain.md
I recently encountered a new user that was led astray by this document.
First, it implied that it was okay to use unverified import with "trusted and reputable sources," which is just wrong. Replaced that with a warning and moved to the top.
Second, it referred to the Monero software as "the wallet" or even "your wallet," which led the user to the location of, well, their wallet file, instead of the binaries. 
Lastly, it seems that people are doing this because they somehow just assume it will be faster. I'm pretty sure the reverse is true, which means that no one should need this tool except for testing and development. This seems worth clarifying at the top.
Also fixed some capitalization.
> Fix confusion and add warning in blockchain import guide

- _data/downloads.yml
See https://old.reddit.com/r/Monero/comments/hpn8i0/hashes_dont_match/
The hashes on the blog post (#1066, not deployed yet) and [the signed hashes.txt](https://web.getmonero.org/downloads/hashes.txt) file are correct. The hashes in the downloads page of [Linux 64-bit](https://github.com/monero-project/monero-site/pull/1071/files#diff-69cb2c60ade563f7533c5f5bac421be4R20) and [Windows 64-bit (Zip)](https://github.com/monero-project/monero-site/pull/1071/files#diff-69cb2c60ade563f7533c5f5bac421be4R10) were swapped.
Please double check this PR by verifying the hashes of both archives before merging.
> Fix swapped hashes of 0.16.0.2 for win64 and linux64 in downloads.yml

- _data/lang/ar/navigation.yml
- _data/lang/de/navigation.yml
- _data/lang/en/navigation.yml
- _data/lang/es/navigation.yml
- _data/lang/fr/navigation.yml
- _data/lang/it/navigation.yml
- _data/lang/nl/navigation.yml
- _data/lang/pl/navigation.yml
- _data/lang/pt-br/navigation.yml
- _data/lang/ru/navigation.yml
- _data/lang/tr/navigation.yml
- _data/lang/zh-cn/navigation.yml
- _data/lang/zh-tw/navigation.yml
- _i18n/en.yml
- _layouts/blog_by_tag.html
- blog/index.html
- css/custom.css
- Added separator between posts
- remove all submenus and use only 'blog'
- Add category selector for desktop and mobile
Resolves  #1001
Preview:
> Blog: Use only one 'Blog' menu and add category selector

- .github/workflows/ci.yml
- Bump actions/checkout to v2
- Limit number of posts to be built to 10
Build time reduced from about 6 minutes to 2.20 minutes (rough average)
> workflows: improve performance of github CI

- resources/developer-guides/daemon-rpc.md
See monero-project/monero#6721
> Added documentation for `get_outs` input parameter `get_txid`

- css/custom.css
Closes #1099 
The problem seems to happen only with one tooltip in the Downloads page (CLI wallet -> 'Bootstrap Node' entry -> "Remote Node" tooltip). Seems to be triggered if a tooltip happens to be at the end of a line on mobile. I solved removing the width of the balloon when on mobile, since it's not shown anyway in that case.
> Fix tooltip messing up the width of a page on mobile in some edge cases

- _i18n/en.yml
- _layouts/moneropedia.html
We don't offer navigation buttons in the Moneropedia and other parts of the webste. This becomes a problem when people click on a Moneropedia entry and then want to go back to the index. The only way to do so at the moment is to go up to the navigation menu and click resources -> moneropedia. Users should have the possibility to quickly go back to the Moneropedia index directly from each entry.
I added a simple *&laquo; Back to the Moneropedia* "button" in the `moneropedia` layout, so that every entry will show it at the bottom right:
> Add possibility to go back to the Moneropedia page under each Moneropedia entry

- .github/ISSUE_TEMPLATE/new-merchant.md
To make sure merchants add the name of their business to the title of the issue.
> Partially fill up title for the 'New Merchant' issue template

- css/custom.css
- Fix tooltip on mobile (extra fix #1102)
- Change list-logo-icons padding (40px -> 20px)
- Remove downloads-icons padding
> Fix tooltip + minor improvements

- _config.yml
- _data/lang/ar/footer-1.yml
- _data/lang/de/footer-1.yml
- _data/lang/en/footer-1.yml
- _data/lang/es/footer-1.yml
- _data/lang/fr/footer-1.yml
- _data/lang/it/footer-1.yml
- _data/lang/nl/footer-1.yml
- _data/lang/pl/footer-1.yml
- _data/lang/pt-br/footer-1.yml
- _data/lang/ru/footer-1.yml
- _data/lang/tr/footer-1.yml
- _data/lang/zh-cn/footer-1.yml
- _data/lang/zh-tw/footer-1.yml
- _includes/head.html
- blog/index.html
The autodetection wasn't working as expected. The helper tag is using both url + baseurl, this broke things but not locally (since we build with an empty baseurl), that's why we didn't see it in https://github.com/monero-project/monero-site/pull/1051#issuecomment-648252942.
Also changed the feed from feed.atom to feed.xml. The new structure of the feed broke things for people who are using the old version.
> Fixes to feed

- _i18n/en.yml
- resources/roadmap/index.md
We had other minor point release after 0.16.0.0, but i don't think make sense to clog the roadmap with release dates, which are also easily browsable on the blog. I think would be better to only list major releases in the roadmap.
> Roadmap: add CLI and GUI 0.16.0.0

- _data/merchants.yml
- _i18n/en.yml
- resources/developer-guides/index.md
These two changes have to be made together because, with the current structure, if we remove a section from the merchants page we have to replace it with something else.
- **Moved 'Libraries and helpers' from the merchants page to the developer guides**. Most of the listed repositories were obsolete. I removed almost all of them and replaced with maintained repos (if anybody have more repos to suggest, please let me know).
- **Added section 'Web Hosting' to the merchants page**. We had a big amount of merchants offering web hosting in the 'services' section. Since to not mess up the selector at the top we need to keep the same amount of categories in the merchants page, i thought was a good idea to create a section dedicated to web hosting.
Closes #974
> Remove 'Libraries and helpers' from the merchants page and replace it with 'Web Hosting' + Add ''Libraries and helpers" to the dev guides

- .github/workflows/hashes.yaml
* Download bF's key from GitHub instead of from unreliable keyserver
* Resolve redirects manually instead of checking server
[Example run](https://github.com/00-matt/monero-site/runs/1004401847)
> ci: Fix hash checking workflow

- community/hangouts/index.md
- community/team/index.md
- css/custom.css
- downloads/index.md
- img/external-white.svg
- img/external.svg
This PR and #1138 aim to give a better UX by clarifying to the user what type of link they are about to click. In this specific case i think it's important to tell the final user they are going to be redirected outside getmonero.
> Add icon to external links

- .github/ISSUE_TEMPLATE/new-merchant.md
To be merged after #1131, which removes the 'Library and helpers' section in the Merchants page
> Replace 'Library and Helpers' with 'Web Hosting' in the 'New Merchant' GitHub issue template

- _i18n/en.yml
- downloads/index.md
It's hard and annoying to maintain (and translate in a timely way) and now we have more point releases, which would fix major issues in the precedent versions.
> Downloads: remove 'known issues' dropdown

- community/merchants/index.md
This is useful to avoid "reverse tabnapping" attacks (the merchants page is  very exposed to those) and to limit profiling users  coming from getmonero who visit the merchants listed.
> Open links in the 'Merchants' page in new tab and add 'noreferrer'

- _layouts/base.html
- _layouts/error.html
- _layouts/index.html
Improves SEO and helps browsers offer the content in the right language for the user. Potentially, this could also help language auto detection (#903).
> Add 'lang' attribute to the <html> element to declare language of the page

- README.md
- _config.yml
- _plugins/sitemap_generator.rb
- netlify.toml
We enforce a baseurl with a wrong structure (the baseurl [shouldn't be a full URL](https://byparker.com/img/what-is-a-baseurl.jpg)) and that conflicts with jekyll's structure. As a result, most of the plugins, like jekyll-feed don't behave as they should and break. This was also the cause of several other problems we had in past, like the broken sitemap generator and autodetection of the feed.
A `baseurl` is needed for the i18n plugin to work, so we just feed it with an empty one. The result is that all internal links will be stripped of the domain `https://www.getmonero.org', but the structure of the website shouldn't be affected. I made several tests and i don't expect any disruption, unless some nginx configuration gets in the middle for some reason.
This will also make the …
> Make baseurl empty and adapt README, netlify.toml and the sitemap_generator accordingly

- _i18n/en.yml
- downloads/index.md
Changes:
- Add Nano S and Nano X models
- Capitalize Trezor **M**odel T
- Remove "supported since" wallet versions: it's useless information for most users (old versions don't work anyway because of hard forks)
- Add wallets that support each hardware wallet type
- Add/update links to support pages in Ledger and Trezor websites
> Add Nano S/X; capitalize Trezor Model T; remove wallet versions; add supported wallets

- _i18n/en.yml
- _includes/upgrade.html
The banner specifically mention the 0.17.0.0 release, but we will have at least one point release before the hard fork and there could be more. Better be more generic and link to the Downloads page instead of the blog post announcing 0.17.0.0.
Would be good to merge this along with #1214
> Upgrade banner: Link to Downloads page and make text more generic

- _i18n/ar/resources/user-guides/verification-allos-advanced.md
- _i18n/de/resources/user-guides/verification-allos-advanced.md
- _i18n/en/resources/user-guides/verification-allos-advanced.md
- _i18n/es/resources/user-guides/verification-allos-advanced.md
- _i18n/fr/resources/user-guides/verification-allos-advanced.md
- _i18n/it/resources/user-guides/verification-allos-advanced.md
- _i18n/nl/resources/user-guides/verification-allos-advanced.md
- _i18n/pl/resources/user-guides/verification-allos-advanced.md
- _i18n/pt-br/resources/user-guides/verification-allos-advanced.md
- _i18n/ru/resources/user-guides/verification-allos-advanced.md
- _i18n/tr/resources/user-guides/verification-allos-advanced.md
- _i18n/zh-cn/resources/user-guides/verification-allos-advanced.md
- _i18n/zh-tw/resources/user-guides/verification-allos-advanced.md
`{{ site.baseurl }}` doesn't seem to work inside a block of code.
Thanks charuto for spotting the issue.
> User guides: fix link to hashesh in 'verification-allos-advanced.md'

- _plugins/moneropedia.rb
If an entry is not found in the given language (LANG.yml), we use the English version. This will allow us to only add a new Moneropedia entry title to `en.yml` and not to all language files, reducing the amount of files to edit when adding a new Moneropedia entry from 28 to 15. This is also helpful for Weblate, since the language files should be edited only there or we risk conflicts.
> moneropedia.rb: If an entry is not present in LANG.yml, use English one

- resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md
I've seen some reports by users not being able to set up a working daemon after using this guide, so it's probably outdated. If somebody using this system could confirm the issue and/or update the guide, would be very appreciated.
> User Guides: Mark guide 'CLI Wallet/Daemon Isolation with Qubes + Whonix' as outdated

- _includes/header.html
- css/custom.css
Makes the language selector more visible. We already use the image for the mobile version, so we don't even make a new request.
Preview:
> Navigation: add language img for language selector (desktop)

- _plugins/moneropedia.rb
- css/custom.css
- img/circled-i.svg
Tested on Firefox and Chromium. Please test it on more browsers.
I was thinking of removing the dotted bottom to the internal Moneropedia links. Mostly because i don't like that in general and i thought the link to the Moneropedia entry would look nicer only in bold + the circled 'i' logo. I decided to keep the dotted bottom here only for consistency with the other internal links, but if people agree it would look nicer without, i'll take it out with pleasure :)
> Add 'Circled Information Source' symbol to Moneropedia links

- _config.yml
- css/custom.css
- get-started/what-is-monero/index.md
- resources/moneropedia/ringCT.md
- resources/moneropedia/ringsignatures.md
- resources/moneropedia/stealthaddress.md
Closes #1187
- Remove carousel structure in the 'What is Monero' page and leave only one video: 'Monero: the essentials'
- Move technology specific videos to their moneropedia entry: Ring Signatures, RingCT, Stealth Addresses
- Add aria-label to imrpove accessibility of the videos
If we like this change, i suggest to also create a FAQ entry saying something like "Are there some videos about how Monero works?" and then link to the videos. They are meant to be watched one after another and this new system kinda break that. I'm proposing it because i don't think people actually notice and watch those videos at the moment. Adding a faq with the list of videos in the right order will fix that and will allow us to link to all the videos at the same time.
We have one video missing here: #1188. …
> Reorganize Monero videos

- _i18n/en.yml
> mining: remove 'trusted' when offering the list of pools

- _config.yml
Something went wrong during the rebase of e5de616c31b7aeb7d35a34b8738d205187e70835 and [the change of baseurl](https://github.com/monero-project/monero-site/pull/1164) was reverted. This should be merged ASAP.
> _config.yml: fix wrong baseurl

- _i18n/de/resources/moneropedia/canonically-unique-host.md
- _i18n/de/resources/moneropedia/change.md
- _i18n/de/resources/moneropedia/clearnet.md
- _i18n/de/resources/moneropedia/coinbase.md
- _i18n/de/resources/moneropedia/consensus.md
- _i18n/de/resources/moneropedia/cryptocurrency.md
- Canonically Unique Host
- Change
- Clearnet
- Coinbase
- Concensus
- Cryptocurrencies
> German translation of Moneropedia entries starting with C

- get-started/mining/index.md
The creator is a malicious actor who, beside constantly running disinformation campaigns against Monero, is currently actively attacking the network and its users. I don't see a reason for suggesting his mining software on Getmonero.
> Remove xmr-stak from 'Mining' page

- _i18n/de/resources/moneropedia/account.md
- _i18n/de/resources/moneropedia/address.md
- _i18n/de/resources/moneropedia/airgap.md
- _i18n/de/resources/moneropedia/atomic-units.md
- _i18n/de/resources/moneropedia/block.md
- _i18n/de/resources/moneropedia/blockchain.md
- _i18n/de/resources/moneropedia/bootstrap-node.md
- _i18n/de/resources/moneropedia/bulletproofs.md
The following entries were translated:
- Account
- Address
- Airgap
- Atomic Units
- Block
- Blockchain
- Bootstrap Node
- Bulletproofs
Note: The links to other Moneropedia entries (marked with an @) may not work in the preview since the terminology has to be updated with the German terms.
> German translation of Moneropedia entries A - B

- _i18n/ar/resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md
- _i18n/en/resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md
- _i18n/es/resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md
- _i18n/fr/resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md
- _i18n/it/resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md
- _i18n/nl/resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md
- _i18n/pl/resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md
- _i18n/pt-br/resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md
- _i18n/ru/resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md
- _i18n/tr/resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md
- _i18n/zh-cn/resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md
- _i18n/zh-tw/resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md
- resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md
**What I've changed:**
+ Added notice about increasing the daemon workstation's private storage and how to estimate the space needed.
+ Changed `monerod` location in the systemd file to `/usr/bin/monerod` from `/usr/local/bin/monerod` since that is where it is located now.
- Removed the parts about installing monero since it is now preinstalled in Whonix.
+ Changed mentions of `gedit` to `nano` because `gedit` is not installed by default.
+ Set outdated to False
I think the name should be changed to exclude the CLI part since the guide works for both monero-gui and monero-cli but to avoid mismatch between title and filenames I left it out for a later PR.
> Updating "Wallet/daemon isolation with Qubes + Whonix"

- css/custom.css
- resources/roadmap/index.md
The ID was duplicated (as reported by the W3C validator in #1289). Transformed into a class
> roadmap: change 'months' id to css class

- _data/merchants.yml
They recently delisted Monero: https://anycoindirect.eu/en/blog/current-and-upcoming-changes-to-our-platform
> Merchants: remove anycoindirect

- css/custom.css
To increase visibility for visually impaired people and to make the "external" image blend in better.
Before:
After:
> Use darker color to increase contrast of topnav menu

- community/sponsorships/index.md
We can revert this commit once they fixed the problem. I already tried to contact them in #1290
> Sponsorships: Remove link to fork networking since their certificate is invalid

- _i18n/en.yml
- _layouts/index.html
The network upgrade was about two months ago, i think it's time to remove the warning in the homepage. I also removed the text, so that translators won't waste time translating it. We will have to add new text for the next network upgrade anyway.
> Remove banner 'network upgrade'

- index.html
Fix W3C errors:
- [End tag section seen, but there were open elements](https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fwww.getmonero.org%2F#l528c14)
- [Unclosed element div](https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fwww.getmonero.org%2F#l504c32)
> Add missing DIV tag ('Join the Community' section)

- _layouts/blog_by_tag.html
- blog/index.html
- css/custom.css
The blog pages tend to be long. Adding the arrow-up button here as well to allow people to go back to the top with one click/tap.
I also moved the css related to the button to the general section and deleted the duplicated page-specific classes, so that the button can be used everywhere withou duplicating CSS.
> Add arrow-up button to the blog and move the related CCS to the general section

- resources/developer-guides/daemon-rpc.md
Added with https://github.com/monero-project/monero/pull/7030
> Add 'synchronized' to 'get_info' call in daemon rpc guide

- _i18n/de/resources/user-guides/multisig-messaging-system.md
- _i18n/de/resources/user-guides/tor_wallet.md
- Multisig transactions with MMS and CLI wallet
- Connecting your local wallet to your own daemon over Tor
> German Translation of User Guides (Wallet 2/2)

- resources/developer-guides/daemon-rpc.md
To be merged after https://github.com/monero-project/monero/pull/7156 is merged and included in a release.
> daemon-rpc: Add 'busy_syncing' call to get_info

- _data/merchants.yml
It was probably removed by mistake. See https://github.com/monero-project/monero-site/pull/1121#issuecomment-752035275
> Merchants: readd Monerojobs.com

- _i18n/de/resources/user-guides/mine-to-pool.md
Adjusted two parts in the German translation of a user guide (How to mine on a pool with XMRig) because I couldn't fix it before #1327 got merged.
> Adjusted the German Translation of a User Guide

- _includes/header.html
- community/workgroups/index.md
Now that #1260 is merged and live, we should change the URL of the Workgroups page from `/community/teams/` to `/community/workgroups/`.
@binaryFate we will need to set up a redirect.
> workgroups: change URL to /community/workgroups/

- _i18n/en.yml
- downloads/index.md
Add 'release notes' link that points to the category "Releases" of the blog for both CLI and GUI releases.
Open to suggestions for a better place for this.
> Downloads: add link to release notes

- _data/merchants.yml
Don't list Monero anymore:
- alagoria.com
- bitvape.com.au
Don't exist anymore:
- congrevape.com/shop
- mycopycorner.com
- cryptonic.net/
See https://www.reddit.com/r/Monero/comments/kp1v6a/what_are_you_using_your_monero_for/ghvea0p/ (not all links were broken)
> Merchants: remove merchants

- _i18n/en.yml
The page is being actively translated. The papers are not, but i guess people expect that, no need to specify anything.
> MRL: remove '(English)' from page header

- _i18n/en.yml
- resources/research-lab/index.md
Makes sense to link to the Library from the MRL page.
Preview:
> MRL: Add new box with button-link to Library

- resources/roadmap/index.md
'checked' is used to specify which tab the user will be directed to when viewing the Roadmap. We use it only for the current year (2021)
> roadmap: remove 'checked' from 2020

- _i18n/en.yml
Translators confuse it with the verb.
> dev guides: make 'g' in 'go' uppercase

- _i18n/en.yml
- get-started/contributing/index.md
We used to link to this page from the 'Team' page. I removed it from there, but i think they have very useful info and statistics, so i'm adding the link in the 'Contributing' page.
> contributing: add link to openhub

- _i18n/en.yml
- get-started/faq/index.md
Removed 'Monero:' from the Essentials link and added an i18n key for Ring CT.
> FAQ: Standardize video hyperlinks

- _i18n/nb-no/resources/user-guides/Offline_Backup.md
- _i18n/nb-no/resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md
- _i18n/nb-no/resources/user-guides/howto_fix_stuck_funds.md
- _i18n/nb-no/resources/user-guides/importing_blockchain.md
- _i18n/nb-no/resources/user-guides/ledger-wallet-cli.md
- _i18n/nb-no/resources/user-guides/mine-to-pool.md
- _i18n/nb-no/resources/user-guides/monero-wallet-cli.md
- _i18n/nb-no/resources/user-guides/monero_tools.md
- _i18n/nb-no/resources/user-guides/node-i2p-zero.md
- _i18n/nb-no/resources/user-guides/prove-payment.md
- _i18n/nb-no/resources/user-guides/remote_node_gui.md
- _i18n/nb-no/resources/user-guides/restore_account.md
- _i18n/nb-no/resources/user-guides/restore_from_keys.md
- _i18n/nb-no/resources/user-guides/securely_purchase.md
- _i18n/nb-no/resources/user-guides/solo_mine_GUI.md
- _i18n/nb-no/resources/user-guides/tor_wallet.md
- _i18n/nb-no/resources/user-guides/verification-allos-advanced.md
- _i18n/nb-no/resources/user-guides/verification-windows-beginner.md
- _i18n/nb-no/resources/user-guides/view_only.md
- _i18n/nb-no/resources/user-guides/vps_run_node.md
Norwegian translation of the User Guides files:
– node-i2p-zero.md
– restore_account.md
– restore_from_keys.md
– securely_purchase.md
– solo_mine_GUI.md
– tor_wallet.md
– verification-allos-advanced.md
– verification-windows-beginner.md
– view_only.md
– vps_run_node.md
– monero-wallet-cli.md
– monero_tools.md
– mine-to-pool.md
– ledger-wallet.md
– importing_blockchain.md
– howto_fix_stuck_funds.md
– cli_wallet_daemon_isolation_qubes_whonix.md
– ledger-wallet-cli.md
– Offline_Backup.md
– prove-payment.md
> Add Norwegian User Guides (2/2)

- resources/developer-guides/wallet-rpc.md
The verbose flag on the incoming_transfers request doesn't actually exist, and
the key image is always returned. See https://github.com/monero-project/monero/blob/b8f3e44a3f7af299c3d6fbf2d21b78d8c99d6d7d/src/wallet/wallet_rpc_server.cpp#L1851
> wallet-rpc: Remove nonexistent parameter

- blog/index.html
- css/custom.css
The navigation bar on the blog page was nonexistent whenever the width was between 62 and 75 rem.
> blog: update nav bar media query

- downloads/index.md
- get-started/accepting/index.md
- get-started/what-is-monero/index.md
- index.html
Lazy loading makes web pages load images only when they are actually
needed (when they need to be displayed to the user), thus saving
resources for both host and users and improving performances for the
latter.
| Page | Page weight before (load time) |  Page weight after (load time) | Space savings (time savings)
|---|---|---|---|
|index.html | 474 kB (546 ms) | 214 kB (373 ms) | -54% (-31%)
| get-started/what-is-monero/index.md | 320 kB (548 ms) | 246 kB (525 ms) | -23% (-4%)
| get-started/accepting/index.md | 254 kB (747 ms) | 193 kB (536 ms) | -24% (-28%)
| downloads/index.md | 397 kB (595 ms) | 243 kB (383 ms) | -38% (-35%)
(tests ran locally)
This should work our of the box on Firefox and Chrome.
https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading
> Improve performance of some pages by lazy loading images

- css/custom.css
- downloads/index.md
- get-started/accepting/index.md
- get-started/what-is-monero/index.md
- index.html
Requires #1508 
Adds width and height attributes to lazy-loaded images. Allows browsers to calculate the aspect ratio and allocate adequate space to avoid layout shifting.
https://www.youtube.com/watch?v=4-d_SoCHeWE
> reduce CLS when lazy-loading images

- meta/manifest.json
I'm not sure what I'm touching here, but these paths seem to be wrong.
> meta: wrong icon path

- _data/merchants.yml
We've tried to exchange 5000 USDC to 14.00667577 XMR which was equivalent to $5000 US plus fees.
Bacrypt has a timer set for every exchange you make, it's about half an hour.
The coins were were transferred to the Bacrypt's wallet about 15 minutes before the timer expiration.
Once the timer has expired, the *money was never transferred to our wallet.*
Here is the *proof of the transaction:* 0x0abc8daeccc0e57bc1fbd02ee04c59ae61c2521e3b97566447994e796822eedf
You can also view here: https://etherscan.io/tx/0x0abc8daeccc0e57bc1fbd02ee04c59ae61c2521e3b97566447994e796822eedf
Here is our conversation with the support team:
Q: "Can you confirm that you’ve received the funds?"
A: "This USDC address does not belong to our service."
Q: "It looks like one of your wallets: …
> Removing *Bacrypt.com* - WARNING, SCAM Website!

- css/custom.css
- index.html
Current issue:
- the double flex causes the string to line up in the center when it no longer fits on the screen, in other words it'll show "...rn more about mo..." instead of "learn more ab...". If you prefer the other behavior, I can change it.
- `overflow: hidden;` isn't really necessary but it increases readability on very small screens.
> home: properly align main button

- downloads/index.md
MyMonero is available on Android as shown on the top banner on their website https://mymonero.com/ (plays store link here https://play.google.com/store/apps/details?id=com.mymonero.official_android_application).
> Add Android icon for MyMonero

- community/sponsorships/index.md
Was removed with #1351
This reverts commit 813d4fe505353742a99f42eafc533c4e1d33db9c.
> Sponsorships: readd link to fork networking

- _data/merchants.yml
According to Bitqist via [a tweet from 21 May 2020](https://twitter.com/bitqist/status/1263438451715854336), they have been absorbed by another exchange called Bitvavo and no longer offer services.
> remove bitqist from the list of exchanges

- _includes/onion.html
onion.html now points to the page the user is on. The onion-location
button will point to this page instead of the homepage.
closes #1571
> make onion link point to the currently visited page

- README.md
We don't need to keep a TOC anymore now that Github provides one automatically for markdown files.
Also updating instructions for translators now that the user guides are almost all on Weblate (ref #1270)
> README: update instructions for translators and remove TOC

- _data/merchants.yml
The [instaex.io](https://instaex.io/) website has been for some time (I do not know precisely how long). The last activity on their [Reddit](https://www.reddit.com/user/instaex/posts/), [Medium](https://instaex.medium.com/), [Facebook](https://www.facebook.com/instaex.io) and [Twitter](https://twitter.com/search?q=%40instaex_io&src=typed_query&f=live) accounts is right around the end of November, 2020 (and their [Twitter account](https://twitter.com/instaex_io) no longer exists).
Additionally, an email I sent to the address they had [previously posted on their website](https://archive.ph/XC8va#selection-347.0-347.13) was undelivered.
> merchants: remove instaex.io

- _i18n/en/resources/user-guides/verification-allos-advanced.md
Numbers messed up the structure of the TOC and were not really needed. Removing them (and the submenu) makes also life much easier for translators.
> user guides: simplify toc and remove numbers from verification-allos-advanced.md

- _data/merchants.yml
About six and a half months ago, _The Decrypt_ [reported](https://decrypt.co/47508/shapeshift-quietly-delists-monero-privacy-coin) that ShapeShift delisted Monero (and ShapeShift [confirmed](https://decrypt.co/47823/shapeshift-confirms-regulatory-risk-led-to-privacy-coin-delistings) this):
> ShapeShift has delisted prominent privacy coin Monero from its platform, a ShapeShift spokesperson told Decrypt via Twitter.
I don't believe Monero has been added back. If this is the case, I propose we remove it from the merchants list for the time being.
> merchants: remove shapeshift

- po4a.config
From the conf file:
```
#
#
```
This configuration file was used for #1639
> add po4a.config to the root of the repo

- _i18n/en/resources/user-guides/monero-wallet-cli.md
There appears to be no such command as `address list`. When I run it I get: 
```
Error: usage: address [ new <label text with white spaces allowed> | all | <index_min> [<index_max>] | label <index> <label text with white spaces allowed> | device [<index>] | one-off <account> <subaddress>]
```
> monero-wallet-cli.md: `address all` instead of `... list`

- resources/roadmap/index.md
- Moved Tryptich and layer 2 to 'future'
- Added atomic swaps are ongoing for 2021
- Ongoing tasks are now shown before upcoming tasks in 'future'
> roadmap: rearrange ongoing and upcoming tasks

- css/custom.css
Some text resulted a bit stacked together.
For example the contributing page:
Before
After
> Add right margin to the img for external links

- _posts/2021-06-24-general-fund-2020-2021-report.md
This is @binaryFate's [reddit post](https://www.reddit.com/r/Monero/comments/o5jlhf/general_fund_20202021_report/) with a couple of minor changes: changed a plaintext URL into a link and changed a link from pointing to the README to pointing to our sponsorships page.
> blog: add general fund report (2020/2021)

- _i18n/en.yml
It's pointless. The link is already in the header.
> library: remove link to masteringmonero in the description

- _data/merchants.yml
- add De-Googled.com (closes #1701)
- move CRYPTODIGGERS.EU from 'echanges' to 'services' (closes #1709)
&nbsp;
- localcoin.is (closes #1711)
- remove trovemat.com (closes #1710)
- remove swaplab (closes #1708)
- remove liberalcoins (closes #1706)
- remove alfacashier (closes #1704)
- remove coincut (closes #1700)
> Add and remove merchants (8)

- _i18n/ar/resources/user-guides/monero-wallet-cli.md
- _i18n/ar/resources/user-guides/weblate/monero-wallet-cli.po
- _i18n/de/resources/user-guides/monero-wallet-cli.md
- _i18n/de/resources/user-guides/weblate/monero-wallet-cli.po
- _i18n/en/resources/user-guides/weblate/monero-wallet-cli.pot
- _i18n/es/resources/user-guides/monero-wallet-cli.md
- _i18n/es/resources/user-guides/weblate/monero-wallet-cli.po
- _i18n/fr/resources/user-guides/monero-wallet-cli.md
- _i18n/fr/resources/user-guides/weblate/monero-wallet-cli.po
- _i18n/it/resources/user-guides/monero-wallet-cli.md
- _i18n/it/resources/user-guides/weblate/monero-wallet-cli.po
- _i18n/nb-no/resources/user-guides/monero-wallet-cli.md
- _i18n/nb-no/resources/user-guides/weblate/monero-wallet-cli.po
- _i18n/nl/resources/user-guides/monero-wallet-cli.md
- _i18n/nl/resources/user-guides/weblate/monero-wallet-cli.po
- _i18n/pl/resources/user-guides/monero-wallet-cli.md
- _i18n/pl/resources/user-guides/weblate/monero-wallet-cli.po
- _i18n/pt-br/resources/user-guides/monero-wallet-cli.md
- _i18n/pt-br/resources/user-guides/weblate/monero-wallet-cli.po
- _i18n/ru/resources/user-guides/monero-wallet-cli.md
- _i18n/ru/resources/user-guides/weblate/monero-wallet-cli.po
- _i18n/tr/resources/user-guides/monero-wallet-cli.md
- _i18n/tr/resources/user-guides/weblate/monero-wallet-cli.po
- _i18n/zh-cn/resources/user-guides/monero-wallet-cli.md
- _i18n/zh-cn/resources/user-guides/weblate/monero-wallet-cli.po
- _i18n/zh-tw/resources/user-guides/monero-wallet-cli.md
- _i18n/zh-tw/resources/user-guides/weblate/monero-wallet-cli.po
The configuration file for po4all is not working as expected (multiple paths are not supported apparently). I've been testing solutions, but haven't come up with anything that doesn't require changing the structure of the .po file (which in any case it's not a big deal, beside the large amount of files moved around). These language files were updated by replacing `verification-allos-advanced` in the config file and then running po4a.
The structure changed substantially, so some translations got lost in the conversion. Still waiting for Weblate to support markdown file so that dealing with user guides will be much less a PITA.
> user-guides: update language files of monero-wallet-cli.md

- _i18n/en.yml
- css/custom.css
- downloads/index.md
Changes:
- make each button fill 20% of total width (consistent with Blog navigation bar)
- rename "Mobile & Light Wallets" to "Mobile & Light" (not enough space)
Before:
After:
> Downloads: fill width of buttons on menu bar

- README.md
We add a section where we introduce the Kanban board we are going to use to keep track of the status of pull requests. This process is partly automated and PRs will move from one column to another depending by actions performed by maintainers and reviewers (we don't use GitHub's team so the automation capabilities are limited).
The board: https://github.com/orgs/monero-project/projects/1
We have four columns at the moment:
These are PRs that for various reasons are not ready for reviews yet. They might be simple WIP drafts or PRs that were ready for review but needed to be reworked heavily before becoming ready for another review.
PRs that are completed and are waiting for 1 or more reviewers to approve them. This column substitutes the old 'needs review' label, which was applied (usually …
> README: add PR workflow (github's project)

- _posts/2021-09-20-post-mortem-of-decoy-selection-bugs.md
Explains the decoy selection bugs and their impact, and recommends users update to v0.17.2.3 as soon as able.
Note the following section:
> Users should also be aware that the implications of the first bug are not as severe as previously reported. It was [widely publicized](https://decrypt.co/76938/monero-developers-disclose-significant-bug-privacy-algorithm) that as a result of the first bug, some very newly spent outputs observed on chain were guaranteed identifiable as real outputs spent in a transaction, however, *this is not actually the case*. Since publication, we learned that [MyMonero](https://mymonero.com/) — a popular light wallet — has been using a [separate implementation](https://github.com/vtnerd/monero-lws/blob/faa51780f3f8e6c5c0c4235499b95c246e074f29/src/util/gamma_picker. …
> Post-mortem of decoy selection bugs

- _posts/2021-09-20-post-mortem-of-decoy-selection-bugs.md
Links to the moneropedia don't work if this snippet is not included.
Ref #1831
> activate moneropedia links to post mortem of decoy selection blog post

- _i18n/en.yml
- resources/tools/index.md
and transfer the content of the old section in the merchants page.
One service was removed (livingroomofsatoshi.com) because doesn't
look like they support Monero.
As mentioned in https://github.com/monero-project/monero-site/issues/1736#issuecomment-884103952
**Requires**  #1743
> tools: add section 'payment gateways'

- resources/developer-guides/wallet-rpc.md
Closes #1849 
The example for the validate_address wallet-rpc call is incorrect.
Parameter values for any_net_type and allow_openalias are shown as
string values instead of boolean. Also, the param object is
incorrectly being set with an equals sign but it should be a colon.
> developer-guides: wallet-rpc: fix validate_address example

- README.md
- add snippet to blog post template to link to moneropedia entries
- fixed markdown formatting where necessary
- removed redundant or unnecessary sections
- update instructions to translate the Moneropedia
- general updates
> README: updates and format fixes

- resources/developer-guides/daemon-rpc.md
I tested all the current calls and updated their description in our RPC guide for the daemon.
~~This is still a work in progress, i tested all the calls but many definitions need to be updated. Any help would be highly appreciated.~~
~~grep `TODO` to find the definitions that still need to be updated.~~
part of #1434
> daemon-rpc: update output of all calls and their description

- _i18n/en.yml
I see some problems in current text: 
`The following are mobile or light wallets that are deemed safe by respected members of the community. `
"Following" what? There is no subject in this sentence.
`If there is a wallet that is not on here, you can request the community check it out.`
I think it should be "you can request the community **to** check it out".
This PR fixes both these problems and also adds a warning that it can be risky to use wallets that are not listed on the getmonero Downloads page.
> Downloads: rewording of Mobile & Light Wallets introduction text

- _i18n/en.yml
"Background" makes little sense when it refers to the M only, not the background. This uses "Transparent M" and "White M (Suggested)".
Even if other changes are to be made on this page later, this change will make the situation far clearer to everyone.
> Far clearer white M wording on Press Kit page

- _i18n/en.yml
- resources/roadmap/index.md
Haveno is arguably one of the most important projects in Monero history, makes sense to add it to the roadmap.
> roadmap: add haveno

- css/custom.css
> css: fix missing margin top in guides

- _i18n/en.yml
Changed "Monero is the only cryptocurrency where every user is anonymous by default." to "Monero is a cryptocurrency where every user is anonymous by default." to address issue [1934](https://github.com/monero-project/monero-site/issues/1934)
> Update confidential_para1 to "a" not "the only" cryptocurrency

- resources/user-guides/index.md
The tutorials state that alphabetic order is needed for the [user guides page](https://www.getmonero.org/resources/user-guides/). This was automated by [a script](https://github.com/plowsof/userguide-drafts/blob/main/helper-scripts/user-guide-index-alphabetic/index-alphabetic.py)  i made.
> user guides page alphabetic order

- .github/alphabetic-userguide.py
- .github/workflows/alphabetic-userguide.yaml
Test will fail on push/pr of the user-guide index page if its not in alphabetic order / succeed if it is. will help repo maintainer with #1967 . (there is an easy-guide.py script to help with creating a guide / auto alphabetic ordering too, not in this PR) 
help for reviewer : im new to workflows so 'the names for jobs' may be wrong / vague 
To test, a PR can be made to [this repo](https://github.com/plowsof/userguide-drafts/blob/main/resources/user-guides/index.md) where the same script is being used (the index is currently in alphabetic order)
> Workflows: userguide index alphabetic test

- _i18n/en/resources/user-guides/tor_wallet.md
fix broken link to the anonymity networks doc page at the bottom (missing "docs" in the site path)
> Update tor_wallet.md : fix link to ANONYMITY_NETWORKS.md  

- get-started/faq/index.md
The "More info" link at https://www.getmonero.org/get-started/faq/#anchor-contribute currently redirects to https://www.getmonero.org/get-started/accepting/ instead of to https://www.getmonero.org/get-started/contributing/, which seems to be the correct one given the names.
> fix: change "More info" link in "How can I contribute?" section of FAQ

- README.md
There is no more `_data/lang` folder (although it existed when the removed line was added to the REAME - see https://github.com/monero-project/monero-site/tree/325ceecd3293ea04edf891ef3e655878d85249fa/_data/lang).
> fix: remove last item on 'General change recommendations'

- _i18n/en/resources/moneropedia/address.md
Some exchanges have 8 to start their wallets: Binance, Bitfinex, KuCoinhave wallet adresses starting with digit '8'.
And the monero donate address starts with an 8, so saying they start with 4 might be confusing as alphatomcat said.
Closes #1947
> Added 8 to make example more clear

- resources/developer-guides/wallet-rpc.md
https://github.com/monero-project/monero/issues/5611
added `(outgoing transactions only)` next to destinations as per https://github.com/monero-project/monero/issues/5992#issuecomment-552457929
> edit get_transfer_by_txid description

- downloads/index.md
Closes #2029
Edge and MyMonero haven't upgraded to the latest network version
(v16) yet. Removing them resulted in the remote sync section to
become empty, so we hide the entire section.
> downloads: hide remote sync section until wallets upgrade to v16

- _i18n/en/resources/user-guides/multisig-messaging-system.md
As reported by throwawayaccount12 on Matrix:
> When you go to the page https://web.getmonero.org/resources/user-guides/multisig-messaging-system.html#the-architecture-of-the-mms and click the Kovri hyperlink, it redirects to a strange site that attempts to force you to install an add-on in your browser. I am using Firefox. If you wait long enough, it will redirect you to a Russian escort page.
I initially wanted to remove only the link, but since kovri is long time gone, makes sense to remove the entire paragraph.
Note that this document probably needs a complete review, as some parts might be obsolete.
> user guides: remove link and reference to kovri in multisig-messaging-system.md

- _i18n/en.yml
- resources/tools/index.md
All explorers listed on the page don't have Tor Onion Service (aka hidden service) available, so I added P2Pool's explorer.
> add links to p2pool block explorer

- _i18n/en/resources/user-guides/remote_node_gui.md
update remote_node guide to include direct link to monero.fail . I came across someone on the reddit monero support thread having troubles because they followed this guide and used outdated information from moneroworld. For those wanting a remote node, the current most up to date list of remote nodes is found on monero.fail
> update remote_node guide to include direct monero.fail

- _i18n/en.yml
- _includes/head.html
- blog/index.html
- community/hangouts/index.md
- community/merchants/index.md
- community/sponsorships/index.md
- community/workgroups/index.md
- downloads/index.md
- get-started/accepting/index.md
- get-started/contributing/index.md
- get-started/faq/index.md
- get-started/mining/index.md
- get-started/what-is-monero/index.md
- library/index.md
- press-kit/index.md
- resources/about/index.md
- resources/developer-guides/index.md
- resources/moneropedia/index.md
- resources/research-lab/index.md
- resources/roadmap/index.md
- resources/tools/index.md
- resources/user-guides/index.md
posting a link to getmonero on social medias results, except few exceptions, in showing a standard description for all pages. This adds dedicated meta descriptions for every page. It will improve getmonero's seo score and links on social media will look nicer and will be more descriptive
- Once translated, these descriptions will show up in the correct language (for example if somebody links to the French version of the "about" page, the description on social medias will be displayed in French)
- Some pages had already a short description usable for meta descriptions, so i used that. An additional advantage is that some are alread translated, so will show up in the correct language right away
To test the before and after, use https://www.opengraph.xyz/
Example of twitter card for the …
> add dedicated meta descriptions

- _includes/head.html
As for https://github.com/monero-project/monero-site/pull/2155#issuecomment-1515528330.
Browsers seem to ignore multiple slashes, but the url should be fixed anyway
> head: fix double slash in og:url

- _i18n/en.yml
I changed monerobenchmarks.info to xmrig's one because the old link redirects to an article that doesn't show benchmark hash-rates and shows only a few CPU's benchmarks. 
closes #2173
> _i18n: change benchmarks page link to better one

- community/merchants/index.md
XMR does not always show up as an option (most likely due to blocking some countries, this can be overcome with VPN or selecting the appropriate tor exit node). Nevertheless, **fixedfloat.com** seems to be the only swapper that offers BTC lightning to Monero.
> Adding a swapper

- _i18n/en/resources/user-guides/verification-allos-advanced.md
Some of links in user-guide post https://www.getmonero.org/resources/user-guides/verification-allos-advanced.html were invalid and doesn't work correctly.
Then I changed also the name of link because the number name which is nowhere in article is confusing for readers in my opinion...
> Fix links and names in user-guide post

- _i18n/ar/resources/user-guides/remote_node_gui.md
- _i18n/ar/resources/user-guides/weblate/remote_node_gui.po
- _i18n/de/resources/user-guides/remote_node_gui.md
- _i18n/de/resources/user-guides/weblate/remote_node_gui.po
- _i18n/en/resources/user-guides/remote_node_gui.md
- _i18n/en/resources/user-guides/weblate/remote_node_gui.pot
- _i18n/es/resources/user-guides/remote_node_gui.md
- _i18n/es/resources/user-guides/weblate/remote_node_gui.po
- _i18n/fr/resources/user-guides/remote_node_gui.md
- _i18n/fr/resources/user-guides/weblate/remote_node_gui.po
- _i18n/it/resources/user-guides/remote_node_gui.md
- _i18n/it/resources/user-guides/weblate/remote_node_gui.po
- _i18n/nb-no/resources/user-guides/remote_node_gui.md
- _i18n/nb-no/resources/user-guides/weblate/remote_node_gui.po
- _i18n/nl/resources/user-guides/remote_node_gui.md
- _i18n/nl/resources/user-guides/weblate/remote_node_gui.po
- _i18n/pl/resources/user-guides/remote_node_gui.md
- _i18n/pl/resources/user-guides/weblate/remote_node_gui.po
- _i18n/pt-br/resources/user-guides/remote_node_gui.md
- _i18n/pt-br/resources/user-guides/weblate/remote_node_gui.po
- _i18n/ru/resources/user-guides/remote_node_gui.md
- _i18n/ru/resources/user-guides/weblate/remote_node_gui.po
- _i18n/tr/resources/user-guides/remote_node_gui.md
- _i18n/tr/resources/user-guides/weblate/remote_node_gui.po
- _i18n/zh-cn/resources/user-guides/remote_node_gui.md
- _i18n/zh-cn/resources/user-guides/weblate/remote_node_gui.po
- _i18n/zh-tw/resources/user-guides/remote_node_gui.md
- _i18n/zh-tw/resources/user-guides/weblate/remote_node_gui.po
- po/user-guides/remote_node_gui.config
Removed whitespace at the end of one in ctrl+f: " \`wallet mode\`. " (appeared to be messing with some string replace) - allowed us to pull in (new) ru translations and not break the norwegian ones.
set 'is translated' to yes on the Russian page.
po4a version 0.68
> localization: po/pot files for remote_node_gui guide

- _i18n/en.yml
- community/workgroups/index.md
The outreach workgroup has been inactive for more than 2 years. 
edit: Replaced Outreach workgroup with Seraphis workgroup and removed mentions of mattermost, which is not used anymore.
closes #2185
> workgroups: remove outreach, add seraphis, remove mattermost

- resources/developer-guides/wallet-rpc.md
Fixes incorrect descriptions of the encoding used for addresses. Let's the user know that the primary address is also returned. Includes information on the default behavior when the `address_index` field is omitted. (Note that `address_index` should have been named `address_indices`, as it is in the outputs of `create_address`, but that's not something the documentation can fix.)
> devguides: fixes to the get_address descriptions

- resources/developer-guides/daemon-rpc.md
reported on IRC. in_peers example has out_peers mistakenly
> devguides: daemon rpc fix in_peers example typo

- _i18n/en/resources/moneropedia/unlocktime.md
Locked outputs cannot be used as ring members since the protocol (by design) has no way of knowing which output is the "true" spend inside of a ring signature. Thus, the protocol only validates ring signatures where each member of the ring is properly unlocked.
> Rm paragraph about locked outputs being used as decoys

- _posts/2023-11-04-ccs-wallet-incident.md
after some discussion, a simple summary that points to the meta issue containing all the details has been agreed upon. i have pushed a draft here.
copy of https://github.com/monero-project/meta/issues/916
> blog: CCS wallet incident

- _i18n/en.yml
- library/index.md
Considering Revuo Monero was initially started by Diego 'rehrar' Salazar in 2019, has been, historically speaking the one newsletter under the Core Workgroup umbrella while he was their liason, more than 100 issues were shared via the 'official' Twitter profile, @monero, archive is found on LocalMonero's website and overall its good standing of audience and content, I think it is appropriate for Revuo Monero to be named and linked as well, keeping things cohesive.
> newsletters: add revuo monero

- _posts/2024-03-08-clsag-security-proof-revisions.md
Sarang / CypherStack found issues with the CLSAG security proofs during an audit and offered to write a blog post for us.
~~Should I remove the urgent tag since this doesn't directly impact monero's CLSAG implementation?~~
> blog: add CLSAG security proof revisions

- .github/workflows/hashes.yaml
Current workflow failed on checking the last CLI file name.
Index between CLI and GUI (14-15) needs to be increased by 1 to accommodate new riscv64 file.
> Fix indices used to check CLI and GUI file names in workflow

- .github/workflows/hashes.yaml
Agreed with selsta to use riscv instead of risc in all file names and links for consistency.
> rename risc -> riscv in URL to download binaries

- downloads/index.md
This is the working url that's already used for the desktop link, maybe this was missed
> fix: update cakewallet download link on mobile

- README.md
replaces / closes #2203
small conflict fixed
master has "`/_i18n/en/resources/moneropedia`" and #2203 had "/\_i18n/en/resources/moneropedia"
> fix conflicts for #2203

- community/merchants/index.md
re-considered for listing after their monero swaps are operational again. currently under maintenance.
> merchants: remove fixedfloat

- resources/tools/index.md
txstreet now community hosted, replaced the link with working instance.
> resources/tools: replace txstreet link

- _i18n/en/resources/moneropedia/tail-emission.md
* Update the content by mentioning tail emission is started
* Mention block reward can be less than 0.6 XMR due dynamic block size
> moneropedia: update tail-emission

- README.md
- _i18n/en.yml
- css/custom.css
- resources/roadmap/index.md
- Remove return address proposal which had no activity/development.
- Mark Haveno as completed.
- Remove ring size task which is duplicate of Seraphis.
- Add "proposed task" status.
- Add ideas from Monero Research Lab
> update roadmap for 2024

- resources/developer-guides/daemon-rpc.md
Fixes small things and typos for daemon RPC documentation; does not require deeper review into `monerod`.
Table of fixes in this PR, originally tracked here: https://github.com/Cuprate/cuprate/issues/159.
| Link | Notes |
|------|-------|
| [get_miner_data](https://www.getmonero.org/resources/developer-guides/daemon-rpc.html#get_miner_data) | Example uses non-standard `18082` for RPC port |
| [flush_cache](https://www.getmonero.org/resources/developer-guides/daemon-rpc.html#flush_cache) | Missing space between `curl` command and output in example |
| [add_aux_pow](https://www.getmonero.org/resources/developer-guides/daemon-rpc.html#add_aux_pow) | Missing space between `curl` command and output in example, extra `'` at the end of `curl` command |
| …
> daemon-rpc: small fixes

- resources/developer-guides/daemon-rpc.md
Adds documentation for undocumented daemon RPC calls; requires review into `monerod`.
Table of fixes in this PR, originally tracked here: https://github.com/Cuprate/cuprate/issues/159.
| Endpoint | Definition | Notes |
|----------|------------|-------|
| `/get_transaction_pool_hashes` | [rpc/core_rpc_server.h @ 125](https://github.com/monero-project/monero/blob/cc73fe71162d564ffda8e549b79a350bca53c454/src/rpc/core_rpc_server.h#L125), [rpc/core_rpc_server_commands_defs.h @ 1625..L1635](https://github.com/monero-project/monero/blob/cc73fe71162d564ffda8e549b79a350bca53c454/src/rpc/core_rpc_server_commands_defs.h#L1615-L1635) | This is the same as `/get_transaction_pool_hashes.bin` but it returns `tx_hashes` as a JSON array instead of binary |
| `/get_public_nodes` | [rpc/core_rpc_server.h @ …
> daemon-rpc: docs for undocumented endpoints

- _i18n/en.yml
Monero outreach went offline, replaced with Youtube playlist.
Youtube link can be changed when uncompressed videos are re-uploaded to other video sharing platforms.
> faq: replace "Breaking Monero" links with Youtube

- css/custom.css
- resources/roadmap/index.md
Closes https://github.com/monero-project/monero-site/issues/2325
- reduced the trigger width for moving from header view to inline view (use header view unless very narrow viewport)
- slightly reduced header font size
- abbreviated the years
> resources: roadmap > upd8 portrait layout

- _includes/header.html
we're putting whitespace into the raw html files due to not using any [whitespace control](https://shopify.github.io/liquid/basics/whitespace/) in the liquid script which decides what locale to add to the homepage url.
This can effect plugins which parse/edit urls such as [jekyll-loading-lazy](https://github.com/monero-project/monero-site/issues/2235#issuecomment-2229061200) which we dont actually need but its just bad practice and could effect other plugins in the future.
if we inspect the monero logo / homepage shortcut in the header at getmonero.org we see:
with this change:
> _includes/header.html: liquid whitespace control

- _i18n/en.yml
- get-started/contributing/index.md
> contributing: add view key + primary address

- _i18n/en.yml
- resources/user-guides/index.md
- resources/user-guides/node-i2p-zero.md
- replaces i2pzero guide with i2pd
- Includes tor p2p guide
- link directs to docs.getmonero.org
requires: https://github.com/monero-project/monero-docs/pull/66
closes: https://github.com/monero-project/monero-site/issues/2277
> userguides: i2pzero migration

- _i18n/en.yml
- resources/user-guides/index.md
- resources/user-guides/vps_run_node.md
replace the outdated how to run guide with newer one at docs.getmonero.org
> user guides: replace outdated how to run node guide

- README.md
#2428 
neither monero core or gui mention this factoid. currently the merge list is created with pen and paper / organised on irc with a .merges bot created by dsc
> README: remove PR workflow section

- community/merchants/index.md
Monerica.com (started in January 2022) is a community maintained directory for Monero businesses and resources. Adding it as a resource to this section is of great value to the Monero community.
> Add Monerica to merchant directory

- community/workgroups/index.md
The linked site is dead. The [last time it was crawled by the Wayback Machine](https://web.archive.org/web/20250421084559/http://communityworkgroup.org/) (April 21, 2025) it was "available for sale".
> Remove dead website communityworkgroup.org

- _posts/2025-08-26-monero-0.18.4.2-released.md
- _posts/2025-08-26-monero-GUI-0.18.4.2-released.md
- _posts/2025-08-26-post-mortem-of-find-and-save-rings-bug.md
i have added a hyperlink to the 'monero GUI v0.18.4.2' blog release as this also contains a link to the CLI
> blog: post mortem of find_and_save_rings() bug
