monero-project/monero-site

knowledge-base/people.md
I want to keep the writers' styles as much as possible, while providing consistency across the whole page/site. Obviously much of the style argument is going to be personal preference, as we come from many different backgrounds, and even the academics can't agree. I've made all the descriptions into standard complete sentences. The Oxford comma will be applied across the board. Please discuss with me any ideas/feelings you have.
=> Stylistic Editing

research-lab/index.md
Gives a way to access the labs from the site.
=> Adding a link to lab.getmonero.rg

_data/merchants.yml
Added Goods after discussion with fluffypony
Added cryptonit.net under this section
Used the esperanto form of monero. This has implication, because so far we avoided the matter of choosing because we avoided the plural. This doesn't mean only English plural or only Esperanto plural is accepted - both could, like both color and colours are accepted. Still, style-wise, it is better to stick to one word (color everywhere or colour everywhere) so this question still remains for -s vs -j.
=> New section and, website, grammar question

_data/donators.yml
=> Updated IOURZZZ's donation

_data/donators.yml
Various additions fixed a bug in raska's history.
=> Adition and fixes

downloads/index.md
added instructions where to put blockchain bootstraps.
Crap, forgot to add two spaces after each line to make markdown goto next line, and can't figure out how to edit before pull. BAH.
=> where to place blockchain bootstraps

_data/donators.yml
Added palexander with 50 coin donation
=> Added palexander

_data/donators.yml
Fix Quantum's donation to be under palexander
=> Updated Donators

_data/merchants.yml, getting-started/merchants.md
Overhauled the merchants directory - removed 1 dead service, added several others I have heard of. Ordered all of the services in alphabetical order to avoid confusion/arguments/etc why something is listed before others or vice-versa.
=> Update merchants directory

_strings_en.yml
Comments welcome, esp. on L53 & L63.
=> _strings_en.yml styling

knowledge-base/moneropedia/stealthaddress.md
Sometimes trying to break stuff like this down results in awkward sentences. Feedback pls.
=> Flesh out stealth addresses a bit

_includes/header.html
CSS menu for the main monero site.
Needs the updated bootstrap.css as well as the main.css from the forum.
=> Full CSS menu without JS.

knowledge-base/about.md
I'll finish the other version at some point, but this is a better written introduction;.
=> copied text from about2.md to about.md,

knowledge-base/people.md
- fix LucaseJones to LucasJones
- fix Gingeropoulos to Gingeropolous
- remove Atrides, he didn't make a "massive contribution", the
contribution actually went the other way
=> people: misc fixes

_data/donators.yml
=> Udated Donors

knowledge-base/user-guides/restore_account.md
Add line after ## Operating Systems:  Windows, Linux, Mac.  
Hopefully change (get rid of ###) will correct the formatting on live website.
=> Formatting change

.gitignore, _data/merchants.yml, knowledge-base/developer-guides/wallet-rpc.md, knowledge-base/user-guides/simplewallet.md, knowledge-base/user-guides/vps_run_node.md
Added a guide for running a node on a VPS. Also made various formatting fixes and adjustments, updated simplewallet knowledgebase to reflect certain 0.9 changes. Added and updated some links.
=> updates: simplewallet knowledgebase, vps run node, minor formatting

knowledge-base/projects.md
The text I used was provided by @generalizethis with the issue (s)he opened here: https://github.com/monero-project/monero-site/issues/56
=> crypto-kingdom extra details

knowledge-base/protocol_explanation.md
- The author should review and finalise. My commit changed the numbering as formatting was making points counting start from 1 again.
- Introduced some basic formatting.
=> formatting-improvements-protocol_explanation.md

_data/merchants.yml
Adding to Getting Started with other merchants and services.
=> Add pymonero and Monero Monitor for Chrome

_data/merchants.yml
Adding my new PHP library for simplewallet.
=> add Monero-PHP library to Merchants and Services list

downloads/index.md
Should cut down on people downloading the blockchain by default.
=> downloads: mention syncing from scratch is much faster

README.md, knowledge-base/developer-guides/daemon-rpc.md, knowledge-base/developer-guides/index.md, knowledge-base/developer-guides/wallet-rpc.md
Overview:
- Edit and re-format wallet-rpc developer guide to include more information and examples.
- Create new daemon-rpc developer guide, including examples.
- Add instructions to README for locally serving getmonero.org to test updates.
---
This pull request represents work done for the follow Forum Funding System project:
- "Improving Developer Guides to include Simplewallet examples and Bitmonerod methods and examples"
- https://forum.getmonero.org/8/funding-required/2504/improving-developer-guides-to-include-simplewallet-examples-and-bitmonerod-methods-and-examples
=> wallet & daemon dev guide improvements

knowledge-base/developer-guides/daemon-rpc.md
=> change transaction to payment ID

_data/merchants.yml
As per:
https://www.reddit.com/r/Monero/comments/4kz1j1/monero_has_been_added_to_bitsquare/
=> Add Bitsquare to exchanges

_data/merchants.yml
combine pull request #120 and #121 with cryptostorm listing PR. Listings added alphabetically
=> Combine Web Developer and Bitsquare PRs (120, 121) with Cryptostorm PR.

_posts/2016-06-20-monero-missive-for-the-week-of-2016-06-20.md
=> post for new monero missive 20160620

_posts/2016-06-20-monero-missive-for-the-week-of-2016-06-20.md
=> Forum link. Update 2016-06-20-monero-missive-for-the-week-of-2016-06-20.md

_data/merchants.yml
https://twitter.com/cafintechnet/status/751234501993312256
=> California Fintech Network now accepts Monero payments

_data/merchants.yml
Duplicate entry of "Web Developer - Stefanos".
=> Duplicate entry on merchants.

_data/merchants.yml
proof: https://twitter.com/nestorgames/status/771983691358801920
=> nestorgames

knowledge-base/user-guides/How-to-mine-Monero-XMR-without-a-mining-equipment.md
If you don’t have a profitable mining equipment, nor time or money to invest into building it, you can still mine Monero with NiceHash.
=> added guide How-to-mine-Monero-XMR-without-a-mining-equipment

_includes/footer.html, _strings_en.yml
This will put a link at the bottom of each page, taking the user to the respective github page (which they can then propose edits to).
=> Added "Edit this page" to footer

knowledge-base/about.md
See https://www.reddit.com/r/Monero/comments/55r4ms/monero_promo_video_is_finally_done/ for where it came from.
The video is https://www.youtube.com/watch?v=TZi9xx6aiuY
=> Add "What is Monero?" video to about page

_data/merchants.yml
CryptoMercado
https://www.reddit.com/r/Monero/comments/57dky6/buy_coffee_and_snacks_with_monero_thanks_to/?st=iudr4g9j&sh=03fa9b2a
=> CryptoMercado

_data/merchants.yml
https://www.reddit.com/r/Monero/comments/57mp1c/httpswwwtuxexchangecom_a_new_exchange_for_trading/?st=iudrwry6&sh=5441f09a
=> Tux Exchange

_data/merchants.yml
https://www.reddit.com/r/Monero/comments/57wj11/monero_added_on_cryptogamesnet/
=> Add Crypto Games to merchants

knowledge-base/moneropedia/index.md
To go along with the [Edit This Page] buttons
=> Add an [Add New Entry] button to moneropedia

knowledge-base/about.md
Maybe instead of making it a source code comment, we should actually put the link on the website?
=> Added comment about video's source code

_data/merchants.yml
updated url for my explorer that mwo12 made
=> updated explore.moneroworld.com

_data/donators.yml
I tried to find a logic to the ordering (e.g., date, amount, or alphabetical) and couldn't find any - so I picked alphabetical. I'll make any changes if needed.
=> Donators: add anonimal to 1st Dan on 2016-12-06

knowledge-base/developer-guides/wallet-rpc.md
- Update `monero-wallet-cli` references to `monero-wallet-rpc`
- Add `make_uri` and `parse_uri` methods
=> Updating monero-wallet-rpc documentation

knowledge-base/moneropedia/paymentid.md
-hex option must appear before quantity
=> Fix openssl rand command

knowledge-base/people.md
Update out of date people list.
=> Update out of date people list.

knowledge-base/developer-guides/wallet-rpc.md
Updating the transfer and transfer_split information within the system.
=> Update wallet.md w/ new responses from the system.

knowledge-base/developer-guides/wallet-rpc.md
Documentation for `get_transfers` wallet-rpc method.
I'm not sure what it actually does, for example whether monero-project/monero#1825 is intentional or a bug. I'll update this while I figure things out.
=> get_transfers documentation

_data/merchants.yml
=> added new merchant (Azur Samui)

knowledge-base/moneropedia/block.md
Per https://github.com/monero-project/monero/commit/4fea1a5fe7de41ebf0fb40be856d8a3f1775e7c6
=> Blocks are created every 2 minutes now

_posts/2016-12-22-monero-core-gui-beta-released.md
people keep going to 2nodez for some reason. It doesn't exist, except for a redirect.
=> changed open node directory / address

_data/merchants.yml
Added new VPS host to merchant list.
=> added new merchant (Rootbox.host)

_data/merchants.yml
Hi
This PR fix 2 broken links and resolve the following issues:
- https://github.com/monero-project/monero-site/issues/258
- https://github.com/monero-project/monero-site/issues/264
- https://github.com/monero-project/monero-site/issues/276
- https://github.com/monero-project/monero-site/issues/278
=> Updated merchants list and fixed broken links

_includes/header.html, get-started/contributing/index.md
- Reverted link in Contributing to forum.getmonero.org
- Reverted header links to forum.getmonero.org
=> Reverted FFS links

get-started/faq/index.md
=> Fix FAQ typo

_includes/header.html, get-started/contributing/index.md
=> [urgent] Fix user-facing broken forum links

_data/merchants.yml, get-started/what-is-monero/index.md
Fix typo that is breaking the link. Sorry, my mistake
=> fix broken links merchants.yml + what-is-monero

resources/user-guides/index.md, resources/user-guides/mining_with_xmrig_and_docker.md
Adding a guide for mining with xmrig within an Alpine Linux docker container.
If this is not something we are looking for in a guide let me know but as it allows a miner to work cross distribution without worrying about dependencies or how to compile it. 
I thought it would be good for new linux users.
=> Adding user guide: mining with docker and xmrig

resources/user-guides/index.md, resources/user-guides/restore_from_keys.md
Looks good on my local system. I'm open to critique, please tell me if if you see ways I can improve my work!
=> New User Guide - Restore from Keys

resources/moneropedia/smartmining.md
This feature has existed for some time, and the documentation should be updated to reflect that!
=> Update smart mining

CONTRIBUTING.md
I've added myself to b5b823f because apparently no one else caught (or didn't have the technical knowledge to catch or possibly flat-out didn't care about) https://github.com/monero-project/monero-site/pull/292#issuecomment-315559220.
=> Docs: add contributing guide and C4 with C4 addendum

_data/merchants.yml
=> Add SilverRound.com to merchants list.

_data/team.yml
I prefer for this name to be referenced.
=> Change my name

resources/moneropedia/tail-emission.md
=> Create tail emission Moneropedia entry

community/hangouts/index.md
=> Remove reference to Telegram

VULNERABILITY_RESPONSE_PROCESS.md, _includes/header.html, _strings_en.yml, resources/vrp/index.md
As discussed in Kovri meetings, IRC, https://github.com/monero-project/monero/pull/1995, https://github.com/monero-project/monero-core/pull/778, and https://github.com/monero-project/meta/issues/39: here is a formalized VRP. This VRP will aid us in working with researchers and HackerOne.
RFC, WIP.
=> Repo: add Vulnerability Response Process

_data/merchants.yml
Hey
This PR  :
closes #259 - fixed broken link and moved to 'services'
closes #298 - new exchange
closes #287 - new merchant
closes #239 - new merchant
closes #327 - new merchant
closes #347 - new merchant
closes #354 - new merchant
=> Updates merchants list

get-started/what-is-monero/index.md
I have rewritten some of the "What is Monero" section. Please let me know if this is an improvement.
=> Update "What is Monero" page

resources/user-guides/importing_blockchain.md, resources/user-guides/index.md
Hey i know i submitted this pull request before but i made some major errors the last time and i just wanted to start again. hopefully this is fine to be merged and doesn't need to be rebased ?
=> Importing the Blockchain users guide 

index.html
=> Update Home Page

README.md
This PR updates the README.md file to give best practices for GitHub usage. Many of the site contributors are not familiar with git or GitHub, so I feel it will be helpful to include this information in README file.
This PR also suggests closing all issues that are related to the best practices (close issues that are already fixed, close issues that have been asked to be closed, close issues that were fixed in the site redesign.)
The following Issues are either already fixed by the site redesign, fixed by a pull request by a contributor, or have comments from @rehrar requesting closure:
closes #1 (site redesign)
closes #5 (site redesign)
closes #17 (fixed in luigi1111/monero-site#1)
closes #49 (vague issue w/ no responses by poster)
closes #56 (fixed in #98)
closes #62 (vague issue w/ no …
=> Add Github Housekeeping Section to README.md

_posts/2017-09-07-monero-0.11.0.0-released.md
Added a few items, moved the fee-related items next to each other
=> Relnote tweaks

get-started/using/index.md
=> Update "Using Monero" page

_data/merchants.yml
=> Add Liberalcoins

_data/irc.yml, community/hangouts/index.md, css/custom.css
* Move IRC channels into their own yml file
* Add a couple more Monero related IRC channels
* Fix the style of the hangouts page to accommodate for the new channels
=> Cleanup IRC channels

get-started/what-is-monero/index.md
Someone please review and make sure this is now properly corrected.
=> Update "What is Monero" page - formatting/link fix

_data/downloads.yml, css/custom.css
=> Add DragonflyBSD download link

_data/merchants.yml
Not affiliated with Changelly, just cleaning up the list.
=> Remove inactive exchanges

_data/merchants.yml
=> Add NiceVPS.net

resources/research-lab/index.md
I noticed a minor spelling error while I tried to retrieve the whitepaper.
Notes:
* Does not conflict / interfere with PR #369
=> Spelling mistake: anotated -> annotated

resources/developer-guides/wallet-rpc.md
I added the missing methods. Also did some minor changes/fixes on the existing doc. Probably better if someone with more experience reviews the changes. Especially for the "sweep_all" method descriptions of the parameters would be nice.
Is there a simple way to get better looking json output on the monero site (for the example results)?
=> Added missing wallet-rpc calls

resources/moneropedia/change.md, resources/moneropedia/cryptocurrency.md, resources/moneropedia/node.md
* Node
* Change
* Cryptocurrency
Because this part of the site is educational and informational purposes, the target for reading level is for someone who is new to cryptocurrency. (Anybody else would probably not be coming to Moneropedia for answers.)
More technical information can always be added later in a new section at the bottom.
=> Expand Moneropedia stubs

get-started/contributing/index.md
=> Update "Contributing to Monero" page

get-started/mining/index.md
=> Update "Mining Monero" page

index.html
Monero is secure
Do we really want the first sentence about the security of Monero to include "extremely difficult to hack and steal your funds. "  To me that doesn't sound safe for large amounts if it's only "extremely difficult"... and why mention "hack" and "steal" at all?  Further, if you are trying to define "decentralized cryptocurrency" the definition is absolutely NOT "extremely difficult to hack and steal your funds.".  You could say the same of cash in a bank vault, an ATM machine, a centralized currency, or the safe in my basement...  Those are all "extremely difficult to hack and steal" from.  It seems to me we should be explaining what decentralized cryptocurrency is and perhaps state it's the safest method known to mankind to store value, outside of Fort Knox.  Not that its …
=> touching up the wording on the main page

_data/merchants.yml, community/merchants/index.md
* Fix #403
* Alphabetically sort merchants
=> Add allforcrypto.com to merchants.yml and alphabetically sort merchants

community/hangouts/index.md, community/sponsorships/index.md, get-started/mining/index.md, get-started/what-is-monero/index.md, resources/research-lab/index.md
Increases privacy by requiring supported browsers to *not* send a
referer header. Also prevents tabnabbing.
=> Add noreferrer + noopener attributes to blank targets

_data/merchants.yml
=> Add thebigcoin.io to merchants.yml

_data/merchants.yml
=> Add Localmonero to Merchant list

_includes/footer.html
s/channel/channels
add IRC channel #monero-translation
replace Slack with MatterMost
closes #426
=> Footer refresh - Fix typo, add IRC channel, raplace slack with mattermost

resources/moneropedia/denominations.md
* initial entry
* note: kramdown table does not render on GitHub preview
=> [Moneropedia] Add entry for denominations (subunits) of Monero

community/merchants/index.md
* add disclaimer
Over the last month, I've seen several instances (Reddit, Github, IRC, etc) of people who said something along the lines of "it's listed on the Monero site, so it should be okay." I think it's important to add a disclosure to remind users of their responsibility to protect their funds and to think critically about who they do business with.
I'm not certain if this block of text should be at the bottom or the top, suggestions would be helpful. I don't have a jekyll instance set up at the moment, so someone please tell me if the `div` is right and will render properly at the bottom of the page.
=> Add disclaimer to merchant list.

_data/merchants.yml
Atesti makes use of wallet's verify/sign feature to timestamp files/messages by anchoring the signature to a PID via IPFS.
=> Added Atesti to Tools

_data/merchants.yml
=> Add xusah.boutique to merchants list + rearrange in alphabetic order

_data/merchants.yml
=> Add karsha.biz to merchants.yml

_data/merchants.yml
=> Add AirVPN.org to merchants.yml

_posts/2017-09-16-logs-for-the-Community-meeting-held-on-2017-09-16.md, _posts/2017-09-17-overview-and-logs-for-the-dev-meeting-held-on-2017-09-17.md, _posts/2017-09-24-logs-for-the-Kovri-dev-meeting-held-on-2017-09-24.md, _posts/2017-09-30-logs-for-the-Community-meeting-held-on-2017-09-30.md, _posts/2017-10-01-overview-and-logs-for-the-dev-meeting-held-on-2017-10-01.md, _posts/2017-10-06-logs-for-the-Kovri-dev-meeting-held-on-2017-10-06.md
=> Meeting Logs | Community (2017-09-16 & 2017-09-30), Dev (2017-09-17 & 2017-10-01), and Kovri (2017-09-24 & 2017-10-06)

community/hangouts/index.md, community/sponsorships/index.md, get-started/mining/index.md, get-started/what-is-monero/index.md, resources/research-lab/index.md
The values of `rel` attributes must be in a space-separated list according to [W3C](https://www.w3.org/TR/html401/struct/links.html#h-12.2).
@anonimal please review.
=> Fix noreferrer and noopener attributes

css/custom.css
The height will adjust just fine. Was invalid before anyways as height was used two times.
=> Fix grey line below footer

resources/user-guides/restore_from_keys.md
The command line is missing --generate-from-keys option
=> Command line correction

_data/merchants.yml
=> Add marcosaguayo.com to merchants.yml

_data/ffs.yml, _includes/header.html, _layouts/ffs-cp.html, _layouts/ffs-fr.html, _layouts/ffs-ideas.html, _layouts/ffs-ot.html, _layouts/ffs-wip.html, forum-funding-system/proposals/additional-gui-dev.md, forum-funding-system/proposals/documentation-cleanup.md, forum-funding-system/proposals/fp-conference-2017.md, forum-funding-system/proposals/getmonero-redesign.md, forum-funding-system/proposals/improve-devguides-simplewallet.md, forum-funding-system/proposals/justin-local-meetups-1.md, forum-funding-system/proposals/justin-local-meetups-2.md, forum-funding-system/proposals/kovri-end-user-docs.md, forum-funding-system/proposals/monero-integrations.md, forum-funding-system/proposals/monero-subforum-8btc.md, forum-funding-system/proposals/mooo-continuation-programming.md, forum-funding-system/proposals/more-mooo-coding-goodness.md, forum-funding-system/proposals/official-qt-gui.md, forum-funding-system/proposals/release-pool-software.md, forum-funding-system/proposals/whatismonero-produced.md
Reverted 06f6b95 to fix mobile navigation subitems not dropping down
=> Mobile fix

_data/irc.yml
=> irc: add #monero-hardware

_data/merchants.yml
~~Will upload with new merchants as soon as they are [submitted on Reddit](https://www.reddit.com/r/Monero/comments/79w8i7/list_of_servicesmerchantsplatforms_who_accept/).~~
Closes #472 
Closes #473 
Closes #483 
Closes #485
=> Add merchants to list

blog/index.html
=> Fix a little bug

_data/merchants.yml
=> Add 99Stack.com

_data/merchants.yml
=> Add secpoint.com to merchants.yml

index.html
Improving accuracy and wording of information on home page
=> Slight modifications to wording on home page

_data/merchants.yml
=> Add MegaChange.is exchange

_data/merchants.yml
* Judit Mátyus ( closes #491 )
* Trovemat.com ( closes #492 )
=> Add Merchants

.gitignore
See https://github.com/monero-project/monero-site/pull/503
=> Remove unnecessary entries from .gitignore

_data/merchants.yml
Ref [https://www.reddit.com/r/moneromarket/comments/7iiybn/just_officially_launched_my_website_selling_ammo/](https://redd.it/7iiybn)
=> Add Crypto Armory merchant

_posts/2017-12-11-A-note-on-fees.md
=> Fix a typo in 'A note on fees' blogpost

_posts/2017-12-11-A-note-on-fees.md
=> Some fixes and adjustments for the "A note on fees" blogpost

_data/merchants.yml
=> Add cryptolotto to merchants list

_data/merchants.yml
=> Add BunkerVPN to merchants

_data/merchants.yml
=> Add Congrevape to merchants list

get-started/mining/index.md
* Remove old miners
* Replace xmr-stak-* with new, unified xmr-stak
* Add XMRig, XMRig AMD and XMRig NVIDIA
=> Update list of miners

_data/merchants.yml
Project Coral Reef is a listing of new stores accepting Monero as a form of payment. Please add to your list.
=> Add new goods merchant

resources/moneropedia/fluffyblocks.md
=> Create Fluffy Blocks Moneropedia entry

_data/merchants.yml
Source: https://twitter.com/TorGuard/status/950429336498245632
=> Add TorGuard to merchants list

_data/merchants.yml
=> Add ablative.hosting to merchants list

_data/merchants.yml
=> Add INST.US to merchants.yml

resources/about/index.md
=> Fixed typo: instantmine -> instamine

_config/nginx.conf
Latest redirects taken from #290. Is there anything else that got updated in the config in the meantime but wasn't pushed to the git repo @fluffypony ?
Fixes #535
=> Update nginx.conf with new redirects and latest cli/gui versions

_data/merchants.yml
=> Add Renjer Snacks to merchants list

_data/merchants.yml
=> Add merchants hodlmonkey and whattheserver.me

_data/merchants.yml
=> Add DeepWebVPN to merchants list

_data/merchants.yml
add merchant "Stamp Monero"As requested by PM on reddit
Closes #566
=> Add merchants (2)

_data/merchants.yml
Closes #588 
Closes #590 
Closes #595 
Closes #598
=> Add merchants to list (3)

_data/merchants.yml
=> Add Kidsweet to merchants list

_data/merchants.yml
+ Closes #578 
+ Closes #577 
+ Closes #582 
+ Closes #581 
+ Closes #585 
+ Closes #586
=> Add merchants to list (2)

_i18n/en/index.md, _i18n/template/index.md
Reopened with the updated wording applied to the new i18n site as I messed up the rebase on the first one. I kept the tagline as-is due to lack of consensus with that. 
For more info, please see #570 and [relevant reddit thread](https://www.reddit.com/r/Monero/comments/7tftjy/id_like_the_communitys_feedback_on_my_proposed/).
I also tried to avoid the diff to the closing </div> line, but the filetypes are showing up as DOS to me in vim (on linux), and converting to UNIX will modify all line endings in the file and produce a mess of a diff.
=> Tweak headline paragraph as per discussion at #570 (take 2)

README.md
There are currently 2 section 5.5s
=> Fix Section Numbering in README

_data/merchants.yml
=> Add merchant onestopny

_layouts/blog_by_tag.html
Fixed the thing, plz merge @luigi1111 and then plz put on server @fluffypony
=> Fixed blog tag issue

_i18n/en/resources/user-guides/remote_node_gui.md, _i18n/en/resources/user-guides/securely_purchase.md, _i18n/es/resources/user-guides/remote_node_gui.md, _i18n/es/resources/user-guides/securely_purchase.md, _i18n/template/resources/user-guides/remote_node_gui.md, _i18n/template/resources/user-guides/securely_purchase.md
Fixed some typos in the user guides. Not sure if I should only be making the changes in the `templates` directory?
=> Fixing some typos.

_data/merchants.yml
=> Add Webbdo to merchants list

_data/merchants.yml
As requested on reddit by the owner
=> Remove merchant Infield Loan Services

_i18n/es/get-started/faq.md
This is my second contribution. I hope you like it 1260011
=> Translation from English to spanish faq.md 1040 w

_i18n/es/downloads.md
Hello, I´m Ericka Simancas. This is my first contribution to the community. I hope that you can accept me. To continue contributing to this excellent project
=> Translation from English to Spanish downloads.md

_data/merchants.yml
=> Add interactive developer to merchants.yml

README.md, _i18n/en/resources/user-guides/index.md, _i18n/es/resources/user-guides/index.md, _i18n/template/resources/user-guides/index.md
I noticed the lack of order when I was working on some contributions. Better to do this now before it gets too out of hand.
=> Alphabetize user guides page.

_data/merchants.yml
=> Add merchant Hiri to list

_data/merchants.yml
=> Add merchant "bitsler"

_data/merchants.yml
=> Add merchant City Map Decor

_i18n/it/resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md
=> Added Qubes-Whonix User Guide to Italian so the site will build correctly

_data/merchants.yml
=> Add merchant nature provides

_i18n/en/community/hangouts.md, _i18n/es/community/hangouts.md, _i18n/it/community/hangouts.md, _i18n/template/community/hangouts.md
Fix link to hiding tcp miner trafic incorectly set to the crypto primitives & concepts in the stackexchange questions and answers
=> Error in hangout.md files (wrong link to StackExchange)

_data/merchants.yml
=> Add merchant moneroapparel

_data/merchants.yml
=> Add merchant nofraud.co

_i18n/en/resources/user-guides/monero-wallet-cli.md, _i18n/es/resources/user-guides/monero-wallet-cli.md, _i18n/it/resources/user-guides/monero-wallet-cli.md, _i18n/template/resources/user-guides/monero-wallet-cli.md
=> Update info about ringsize in the monero-wallet-cli user guide

_data/merchants.yml
=> Add merchant ppcprotect

_data/merchants.yml
=> Add merchant 'keyring creative'

_i18n/es.yml, _i18n/fr.yml, _i18n/it.yml, _i18n/pl.yml, _i18n/template.yml
- Added pl and fr to each other respectively
- Changed "Polish" to "Polski" in es, tempate, and it
=> Updated language .yml so jekyll will shut up when building

_data/merchants.yml
Please consider adding cryptocurrencytools.org as a new offline javascript tool.
It works like moneroaddress.org but tries to make multisig as easy as possible so it gets used more.
=> Add cryptocurrencytools.org

_data/merchants.yml
=> Some more merchants

_data/merchants.yml
=> Add merchant 'crypto merch global'

_data/merchants.yml
Closes:
- #726 Crypto Clothing 
- #727 Urban Detail
=> Add more new merchants.

_posts/2018-05-28-logs-for-the-kovri-pr-meeting-held-on-2018-05-28.md, _posts/2018-05-29-logs-for-the-kovri-defcon-meeting-held-on-2018-05-29.md
Not sure about summary, tags and author.
=> Meeting Logs Kovri PR (2018-05-28) & Kovri DefCon (2018-05-29)

README.md, _config.yml, _data/events.yml, _data/lang/pl/navigation.yml
- use `bundle exec jekyll serve` to use local jekyll
- change `gems` to `plugins` because it's deprecated
- remove events
=> Small fixes

_i18n/en/resources/developer-guides/daemon-rpc.md, _i18n/es/resources/developer-guides/daemon-rpc.md, _i18n/fr/resources/developer-guides/daemon-rpc.md, _i18n/it/resources/developer-guides/daemon-rpc.md
Reviewed
This PR solves #709
Actually, the Daemon RPC Developer Guide is outdated.
I'm trying to add everything that is actually missing:
- Review each call
- Add missing calls
- Add new inputs/outputs
- Add descriptions
- Update examples
Here is my process for doing this:
1. Check the RPC calls (JSON first) from the [Core RPC Server](https://github.com/monero-project/monero/blob/master/src/rpc/core_rpc_server.h) file.
2. For each RPC call, look it up in the [Command Definition](https://github.com/monero-project/monero/blob/master/src/rpc/core_rpc_server_commands_defs.h) file.
3. Add missing information to the Developer Guide:
1. For a new RPC Call, add it in the Guide, at the same position it is in the list from [Core RPC Server](https://github.com/monero-project/monero/blob/master/src/rp …
=> Developer Guide - Daemon RPC - Full Update

_data/irc.yml
This solves #742.
Actually Work In Progress as it is useless to update hangout page while @rehrar is reworking it for multilanguage reimplementation.
=> Add kovri channels to hangouts page

community/team/index.md, css/custom.css
This solves #750 since #575 broke the CSS
CSS is now overidden for team page to split the header in 5 instead of 6.
Maybe there is a better way to do it, but at least it works.
=> CSS Fix for team page

README.md
@rehrar looks like it only needed few tweaks in the README. Did I miss something here? Waiting your review then i will update the guide on Taiga as well
=> README: edit instructions for translators

_posts/2018-06-07-logs-for-the-kovri-dev-meeting-held-on-2018-06-07.md
https://gist.github.com/selsta/1082f90ae3fc7ce3af414e93ba37287a
=> Meeting Logs Kovri Dev (2018-06-07)

_data/merchants.yml
=> Add merchant ecosystems

_data/downloads.yml, downloads/index.md
- downloads.yml version tag has been separated to two, one for gui and one for cli
- Downloads page has been adjusted to reflect the changes
=> Changed GUI and CLI to have their own versions

_i18n/fr/resources/user-guides/Offline_Backup.md, _i18n/fr/resources/user-guides/create_wallet.md, _i18n/fr/resources/user-guides/easiest_buy.md, _i18n/fr/resources/user-guides/howto_fix_stuck_funds.md, _i18n/fr/resources/user-guides/importing_blockchain.md, _i18n/fr/resources/user-guides/mine-to-pool.md, _i18n/fr/resources/user-guides/mining_with_xmrig_and_docker.md, _i18n/fr/resources/user-guides/monero-wallet-cli.md, _i18n/fr/resources/user-guides/restore_account.md, _i18n/fr/resources/user-guides/restore_from_keys.md, _i18n/fr/resources/user-guides/securely_purchase.md, _i18n/fr/resources/user-guides/solo_mine_GUI.md, _i18n/fr/resources/user-guides/verification-allos-advanced.md, _i18n/fr/resources/user-guides/verification-windows-beginner.md, _i18n/fr/resources/user-guides/view_only.md
This includes the advanced binary verification guide in French, along with typos correction on other user-guides.
=> User guide French Completion

_data/lang/en/roadmap.yml, _data/lang/es/roadmap.yml, _data/lang/fr/roadmap.yml, _data/lang/it/roadmap.yml, _data/lang/pl/roadmap.yml, _data/lang/template/roadmap.yml
This is a small update to the roadmap, to add ledger support as an achievement.
=> Roadmap update (Ledger support)

_posts/2018-03-03-logs-for-the-Community-meeting-held-on-2018-03-03.md, _posts/2018-03-31-logs-for-the-Community-meeting-held-on-2018-03-31.md, _posts/2018-04-14-logs-for-the-Community-meeting-held-on-2018-04-14.md
Tested on the following platforms:
Windows 10 | KO | OK | OK | OK | OK | OK
=> Logs of Community meeting 03-03, 03-31, 04-14

_data/merchants.yml
=> Add monerovision to merchants list

_posts/2018-05-12-logs-for-the-Community-meeting-held-on-2018-05-12.md, _posts/2018-06-09-logs-for-the-Community-meeting-held-on-2018-06-09.md
Tested on the following platforms:
Windows 10 | KO | OK | OK | OK | OK | OK
=> Logs of Community meeting 05-12, 06-09

_posts/2018-04-28-logs-for-the-Community-meeting-held-on-2018-04-28.md, _posts/2018-05-26-logs-for-the-Community-meeting-held-on-2018-05-26.md
A huge thanks to @needmoney90 on this one!
Tested on the following platforms:
Windows 10 | KO | OK | OK | OK | OK | OK
=> Logs of Community meeting 04-28, 05-26

_data/merchants.yml
=> New merchant bitdials.eu

_posts/2018-06-28-logs-for-the-kovri-dev-meeting-held-on-2018-06-28.md
https://gist.github.com/selsta/1082f90ae3fc7ce3af414e93ba37287a
=> Meeting Logs Kovri Dev (2018-06-28)

_data/merchants.yml
Add EXMO and Switchain
Closes #786
=> Add exchanges to merchants list

_i18n/en.yml, _i18n/es.yml, _i18n/fr.yml, _i18n/it.yml, _i18n/pl.yml
The current number of contributors is 436 according to OpenHub, much more than the numbers on the site ("well over 200", "over 240"). But let's be modest and choose a round number:
- "well over 400"
- "over 420"
=> Update number of contributors

_data/merchants.yml
=> New merchants added

_data/merchants.yml
Issue solved for https://github.com/monero-project/monero-site/issues/795 ?
=> Monero added to online store

_posts/2018-07-07-logs-for-the-Community-meeting-held-on-2018-07-07.md
~~Will be tested in a minute~~
Edit : Tested OK on the following platforms:
Windows 10 | OK | OK | OK | OK | OK | OK
=> Community Workgroup Meeting logs from 2018-07-07

_posts/2018-07-21-logs-for-the-Community-meeting-held-on-2018-07-21.md
This is the community meeting logs.
Sorry i wasn't here.
=> Community meeting logs from 07-21

_data/merchants.yml
=> New exchange Bitexbook

_i18n/fr.yml, _i18n/fr/resources/user-guides/How-to-mine-Monero-XMR-without-a-mining-equipment.md
This correct a typo i left in the nicehash french userguide (two markdown links issues) and the using page untranslated snippet removal (i don't get why i missed it).
=> Minor correction to French version

_data/merchants.yml
=> Add new Instant Exchange ChangeHero

_i18n/ar/resources/user-guides/ledger-wallet-cli.md, _i18n/en/resources/user-guides/ledger-wallet-cli.md, _i18n/es/resources/user-guides/ledger-wallet-cli.md, _i18n/it/resources/user-guides/ledger-wallet-cli.md, _i18n/pl/resources/user-guides/ledger-wallet-cli.md
I was reading the guide and found the word "you" mistakenly written. Did the changes and made an issue #821. @el00ruobuob commented and asked me if he would do the PR to correct the word or if I was working on it. I told him I would do the PR. So here it is.
:)
Thank you guys.
=> Proof reading ledger-wallet-cli.md guide fix word

_i18n/ar.yml
This complete #802, i did not see it was missing as #772 was merged a long time ago.
=> Arabic yml stuff missing (Library + moneropedia lang_tag)

_i18n/ar.yml, _i18n/en.yml, _i18n/es.yml, _i18n/fr.yml, _i18n/it.yml, _i18n/pl.yml
This is the update suggested by @dEBRUYNE-1 in #814 for EN and FR only.
@erciccione, update is needed also for IT,ES,PL,AR.
Should i replace those language with the actuel EN sentences?
=> Update Hardware Wallet section of download page (EN,FR)

_i18n/ar/resources/moneropedia/node.md, _i18n/en/resources/moneropedia/node.md, _i18n/es/resources/moneropedia/node.md, _i18n/fr/resources/moneropedia/node.md, _i18n/it/resources/moneropedia/node.md
This update moneropedia node entry with "network upgrades" instead of "hardfork" and month to "October" and "April" Instead of "September" and "March".
This is for AR,EN,ES,FR,IT
PL has already been translated and need to be changed by a polish speaker @erciccione.
=> Update Moneropedia node article - hardfork term and dates

_i18n/ar/resources/user-guides/ledger-wallet-cli.md, _i18n/en/resources/user-guides/ledger-wallet-cli.md, _i18n/es/resources/user-guides/ledger-wallet-cli.md, _i18n/it/resources/user-guides/ledger-wallet-cli.md, _i18n/pl/resources/user-guides/ledger-wallet-cli.md
Hi @el00ruobuob,
Found another word **(original)** to fix in the `ledger-wallet-cli.md` file. Made the fix in the files that aren't translated yet.
:)
=> Proof-reading user-guide/ledger-wallet-cli.md word "original" fix

README.md
Fixes #830, a typo in the Readme.
=> Fixed the smallest Readme typo.

_i18n/en/resources/user-guides/mining_with_xmrig_and_docker.md, _i18n/es/resources/user-guides/mining_with_xmrig_and_docker.md, _i18n/it/resources/user-guides/mining_with_xmrig_and_docker.md
Hi @el00ruobuob,
Found this and created the PR. Made this issue #828 about it. 
:)
=> Proof-reading mining_with_xmrig_and_docker.md guide "Why Docker" section

_data/merchants.yml
=> Add merchant mojave.cafe

_data/merchants.yml
This adds the new merchants listed in #842:
- 1Gbits
- Monovm
- CoinPayment (payment gateway)
=> New merchants

_data/merchants.yml
This solves #846 and #847 and add indacoin.com as instant exchange
=> More new merchants

_data/merchants.yml
=> New exchange - Coindirect

_data/merchants.yml
=> New exchange "Anycoin"

_data/merchants.yml
Add new merchant "Miners For Less".
This solves #859
=> New Merchant

_i18n/en/resources/user-guides/restore_from_keys.md, _i18n/es/resources/user-guides/restore_from_keys.md, _i18n/it/resources/user-guides/restore_from_keys.md
The word "Launch" was missing the "n".
=> Proofreading user_guides restore_from_keys

.github/workflows/ci.yml
https://github.com/selsta/monero-site/actions/runs/69283929
=> workflows: add site CI

_i18n/pt-br/resources/user-guides/prove-payment.md
This is https://repo.getmonero.org/monero-project/monero-site/-/merge_requests/1145 squashed, rebased and ready to be merged (was already reviewed on gitlab) @luigi1111
=> Translating prove-payment.md (pt-BR)

README.md, _data/lang/ar/footer-2.yml, _data/lang/de/footer-2.yml, _data/lang/en/footer-2.yml, _data/lang/es/footer-2.yml, _data/lang/fr/footer-2.yml, _data/lang/it/footer-2.yml, _data/lang/nl/footer-2.yml, _data/lang/pl/footer-2.yml, _data/lang/pt-br/footer-2.yml, _data/lang/ru/footer-2.yml, _data/lang/tr/footer-2.yml, _data/lang/zh-cn/footer-2.yml, _data/lang/zh-tw/footer-2.yml, _includes/disclaimer.html, _includes/untranslated.html, community/merchants/index.md, resources/moneropedia/index.md
=> Change all links to gitlab 'monero-site' repo to github

_posts/2020-04-13-migration-github.md
=> blog: add post about migration from gitlab

.github/ISSUE_TEMPLATE/general.md, .github/ISSUE_TEMPLATE/new-merchant.md
New templates: 'General' and 'New Merchant'
Preview: open an issue on https://github.com/erciccione/monero-site
=> Remove .gitlab folder and add GitHub's issue templates

_i18n/pt-br/resources/moneropedia/fungibility.md
+ changes suggested by netrik182
Recovered https://repo.getmonero.org/monero-project/monero-site/-/merge_requests/1143, rebased and added @netrik182's review
=> [Recovered] Translating fungibility.md (pt-br)

_i18n/pt-br/resources/user-guides/verification-allos-advanced.md
Co-authored-by: @asdrub
This commit was rebased with current github master. Heavily based on MR [1156](https://repo.getmonero.org/monero-project/monero-site/-/merge_requests/1156) from @asdrub, yet updated and complemented by me.
ping @erciccione
=> added pt-BR user-guide to verify hashes

_i18n/ar/resources/user-guides/verification-allos-advanced.md, _i18n/de/resources/user-guides/verification-allos-advanced.md, _i18n/es/resources/user-guides/verification-allos-advanced.md, _i18n/fr/resources/user-guides/verification-allos-advanced.md, _i18n/it/resources/user-guides/verification-allos-advanced.md, _i18n/nl/resources/user-guides/verification-allos-advanced.md, _i18n/pl/resources/user-guides/verification-allos-advanced.md, _i18n/ru/resources/user-guides/verification-allos-advanced.md, _i18n/tr/resources/user-guides/verification-allos-advanced.md, _i18n/zh-cn/resources/user-guides/verification-allos-advanced.md, _i18n/zh-tw/resources/user-guides/verification-allos-advanced.md
Except pt-br, which is being PRd separately (#935)
=> Sync 'verification-allos-advanced.md' with english version for all languages

_i18n/en/resources/user-guides/remote_node_gui.md
Fixed spelling, unnecessary commas, capitalization, and removed trailing new line.
=> Update remote_node_gui.md by fixing grammtical issues, trailing new line

_i18n/en.yml
=> Merchants: point to the disclaimer at the bottom of the page

_i18n/en/resources/developer-guides/wallet-rpc.md
=> wallet-rpc (en): 'restore_height' is 'integer' not 'long'

README.md
The badge will tell us if master builds correctly or something is broken
=> README: Add GitHub actions badge for master build status

_i18n/ar.yml, _i18n/de.yml, _i18n/en.yml, _i18n/es.yml, _i18n/fr.yml, _i18n/it.yml, _i18n/nl.yml, _i18n/pl.yml, _i18n/pt-br.yml, _i18n/tr.yml, _i18n/zh-cn.yml, _i18n/zh-tw.yml, press-kit/index.md
Resolves half of #957
I transferred the translations for all languages to the new structure.
=> Press kit refactoring

_i18n/ar.yml, _i18n/ar/resources/moneropedia/randomx.md, _i18n/de.yml, _i18n/de/resources/moneropedia/randomx.md, _i18n/en.yml, _i18n/en/resources/moneropedia/randomx.md, _i18n/es.yml, _i18n/es/resources/moneropedia/randomx.md, _i18n/fr.yml, _i18n/fr/resources/moneropedia/randomx.md, _i18n/it.yml, _i18n/it/resources/moneropedia/randomx.md, _i18n/nl.yml, _i18n/nl/resources/moneropedia/randomx.md, _i18n/pl.yml, _i18n/pl/resources/moneropedia/randomx.md, _i18n/pt-br.yml, _i18n/pt-br/resources/moneropedia/randomx.md, _i18n/ru.yml, _i18n/ru/resources/moneropedia/randomx.md, _i18n/tr.yml, _i18n/tr/resources/moneropedia/randomx.md, _i18n/zh-cn.yml, _i18n/zh-cn/resources/moneropedia/randomx.md, _i18n/zh-tw.yml, _i18n/zh-tw/resources/moneropedia/randomx.md, resources/moneropedia/randomx.md
=> Moneropedia: add RandomX

resources/about/index.md
Now that https://github.com/monero-project/monero/pull/6314 is merged
=> About: uncomment dandelion++ in 'Technical Info'

README.md
=> README: update instructions to edit library

get-started/faq/index.md
to question 'If Monero is so private how do we know they're not being created out of thin air?'
=> FAQ: add link to blog post about supply auditability

_i18n/en.yml, press-kit/index.md
Based on #959 
~~Review only 3824a8c~~
=> press-kit: add TheMonera's graphics and badges

_i18n/ar/resources/moneropedia/randomx.md, _i18n/de/resources/moneropedia/randomx.md, _i18n/en/resources/moneropedia/randomx.md, _i18n/es/resources/moneropedia/randomx.md, _i18n/fr/resources/moneropedia/randomx.md, _i18n/it/resources/moneropedia/randomx.md, _i18n/nl/resources/moneropedia/randomx.md, _i18n/pl/resources/moneropedia/randomx.md, _i18n/pt-br/resources/moneropedia/randomx.md, _i18n/ru/resources/moneropedia/randomx.md, _i18n/tr/resources/moneropedia/randomx.md, _i18n/zh-cn/resources/moneropedia/randomx.md, _i18n/zh-tw/resources/moneropedia/randomx.md
=> Moneropedia: fix link to RandomX Outreach article

_i18n/ar/resources/moneropedia/scalability.md, _i18n/de/resources/moneropedia/scalability.md, _i18n/en/resources/moneropedia/scalability.md, _i18n/es/resources/moneropedia/scalability.md, _i18n/fr/resources/moneropedia/scalability.md, _i18n/it/resources/moneropedia/scalability.md, _i18n/nl/resources/moneropedia/scalability.md, _i18n/pl/resources/moneropedia/scalability.md, _i18n/pt-br/resources/moneropedia/scalability.md, _i18n/ru/resources/moneropedia/scalability.md, _i18n/tr/resources/moneropedia/scalability.md, _i18n/zh-cn/resources/moneropedia/scalability.md, _i18n/zh-tw/resources/moneropedia/scalability.md
The text was suggested by @SarangNoether in https://github.com/monero-project/monero-site/issues/913#issuecomment-634059685. Feel free to suggest improvements.
Closes #913
=> moneropedia: rewrite 'Scalability' entry

_data/merchants.yml
- iCryptoNode (Closes #955)
- AnonAddy (Closes #960)
- Monero Betting (Closes #965)
=> Add 3 new merchants

_posts/2019-11-23-community-meeting.md, _posts/2019-12-07-community-meeting.md, _posts/2019-12-21-community-meeting.md, _posts/2020-01-04-community-meeting.md, _posts/2020-01-18-community-meeting.md, _posts/2020-02-01-community-meeting.md, _posts/2020-02-15-community-meeting.md, _posts/2020-02-29-community-meeting.md, _posts/2020-03-28-community-meeting.md, _posts/2020-04-11-community-meeting.md, _posts/2020-04-25-community-meeting.md, _posts/2020-05-09-community-meeting.md, _posts/2020-06-06-community-meeting.md
Add missing meeting minutes from 2019-11-23 to 2020-06-06.
=> Add missing community meeting minutes

_i18n/en.yml
=> home: remove 'reasonably' from header

_data/merchants.yml
- CryptoFlooring (closes #991)
- Capsul (closes #1006)
- bitni.com (closes #1022)
- Cryptocurrency Posters (closes #1026)
- Drippin Junkies (closes #1029)
=> Add 5 new merchants

_i18n/ar/resources/user-guides/node-i2p-zero.md, _i18n/de/resources/user-guides/node-i2p-zero.md, _i18n/en.yml, _i18n/en/resources/user-guides/node-i2p-zero.md, _i18n/es/resources/user-guides/node-i2p-zero.md, _i18n/fr/resources/user-guides/node-i2p-zero.md, _i18n/it/resources/user-guides/node-i2p-zero.md, _i18n/nl/resources/user-guides/node-i2p-zero.md, _i18n/pl/resources/user-guides/node-i2p-zero.md, _i18n/pt-br/resources/user-guides/node-i2p-zero.md, _i18n/ru/resources/user-guides/node-i2p-zero.md, _i18n/tr/resources/user-guides/node-i2p-zero.md, _i18n/zh-cn/resources/user-guides/node-i2p-zero.md, _i18n/zh-tw/resources/user-guides/node-i2p-zero.md, resources/user-guides/index.md, resources/user-guides/node-i2p-zero.md
[see on reddit](https://www.reddit.com/r/Monero/comments/gy4bqx/tor_and_i2p_monero_nodes_seen_over_the_last_week/ftcqdga/)
The original version of this guide was originally uploaded by @knaccc on the [i2p-zero repository](https://github.com/i2p-zero/i2p-zero/blob/master/monerod-with-i2p-zero.md).
=> Add user guide 'Run a Monero node through I2P with I2P-zero'

_i18n/en.yml, get-started/faq/index.md
=> Faq: Add 'Why is Monero called 'Monero'?'

_posts/2020-06-26-monero-0.16.0.1-released.md
=> Blog: add post announcing release 0.16.0.1

.github/workflows/hashes.yaml
Whenever hashes.txt is modified, verify the PGP signature, download all of the release binaries, and verify their checksums.
=> ci: Validate hashes.txt

_data/downloads.yml
Not used by the downloads page for some reason, but needed for the verification script (#1074)
=> data: Fix download URLs

_i18n/en.yml, get-started/what-is-monero/index.md
=> Remove references to Kovri in the 'What is Monero?' page

_includes/footer.html, legal/index.md
=> Remove analytics

_plugins/sitemap_generator.rb
We are currently serving broken URLs in the sitemap, which results in bad SEO. Let's get this merged ASAP.
=> Fix URL generation in sitemap generator

_data/merchants.yml
- monerocardgames.com (closes #1047)
- altcoinpostage.com (closes #1041)
- hollaex.com (closes #1055)
- swapswop.io (closes #1059)
=> Add 4 new merchants

_i18n/en.yml, css/custom.css, resources/moneropedia/index.md
=> Moneropedia: add description of the Moneropedia to index.md

_i18n/ar.yml, _i18n/ar/resources/moneropedia/daemon.md, _i18n/de.yml, _i18n/de/resources/moneropedia/daemon.md, _i18n/en.yml, _i18n/en/resources/moneropedia/daemon.md, _i18n/es.yml, _i18n/es/resources/moneropedia/daemon.md, _i18n/fr.yml, _i18n/fr/resources/moneropedia/daemon.md, _i18n/it.yml, _i18n/it/resources/moneropedia/daemon.md, _i18n/nl.yml, _i18n/nl/resources/moneropedia/daemon.md, _i18n/pl.yml, _i18n/pl/resources/moneropedia/daemon.md, _i18n/pt-br.yml, _i18n/pt-br/resources/moneropedia/daemon.md, _i18n/ru.yml, _i18n/ru/resources/moneropedia/daemon.md, _i18n/tr.yml, _i18n/tr/resources/moneropedia/daemon.md, _i18n/zh-cn.yml, _i18n/zh-cn/resources/moneropedia/daemon.md, _i18n/zh-tw.yml, _i18n/zh-tw/resources/moneropedia/daemon.md, resources/moneropedia/daemon.md
=> Moneropedia: add 'Daemon' entry

_i18n/ar/resources/user-guides/securely_purchase.md, _i18n/de/resources/user-guides/securely_purchase.md, _i18n/en/resources/user-guides/securely_purchase.md, _i18n/es/resources/user-guides/securely_purchase.md, _i18n/fr/resources/user-guides/securely_purchase.md, _i18n/it/resources/user-guides/securely_purchase.md, _i18n/nl/resources/user-guides/securely_purchase.md, _i18n/pl/resources/user-guides/securely_purchase.md, _i18n/pt-br/resources/user-guides/securely_purchase.md, _i18n/ru/resources/user-guides/securely_purchase.md, _i18n/tr/resources/user-guides/securely_purchase.md, _i18n/zh-cn/resources/user-guides/securely_purchase.md, _i18n/zh-tw/resources/user-guides/securely_purchase.md
=> Update user guide 'Securely purchasing and storing Monero'

_data/merchants.yml
=> Merchants: update 'BITEXBOOK'

_data/lang/nb-no/footer-1.yml, _data/lang/nb-no/footer-2.yml, _data/lang/nb-no/navigation.yml
Files translated by Chris Avis and sent to me by email. I adapted the translated files with the recent changes and removed some extra newlines.
Note that the website in Norwegian is not available yet, but it's [fully translated on Weblate](https://translate.getmonero.org/projects/getmonero/monero-site/nb_NO/). We are only waiting for a reviewer.
=> data/nb-no: Add footer1.yml footer-2.yml navigation.yml in Norwegian

_i18n/ar/resources/moneropedia/kovri.md, _i18n/de/resources/moneropedia/kovri.md, _i18n/en/resources/moneropedia/kovri.md, _i18n/es/resources/moneropedia/kovri.md, _i18n/fr/resources/moneropedia/kovri.md, _i18n/it/resources/moneropedia/kovri.md, _i18n/nl/resources/moneropedia/kovri.md, _i18n/pl/resources/moneropedia/kovri.md, _i18n/pt-br/resources/moneropedia/kovri.md, _i18n/ru/resources/moneropedia/kovri.md, _i18n/tr/resources/moneropedia/kovri.md, _i18n/zh-cn/resources/moneropedia/kovri.md, _i18n/zh-tw/resources/moneropedia/kovri.md
=> Moneropedia: edit 'Kovri' entry

css/custom.css
=> custom.css: min-width in .btn-fixed

resources/developer-guides/daemon-rpc.md, resources/developer-guides/wallet-rpc.md
=> Fix Moneropedia tooltips not showing in dev guides

_data/lang/ar/footer-1.yml, _data/lang/de/footer-1.yml, _data/lang/en/footer-1.yml, _data/lang/es/footer-1.yml, _data/lang/fr/footer-1.yml, _data/lang/nb-no/footer-1.yml, _data/lang/nl/footer-1.yml, _data/lang/pl/footer-1.yml, _data/lang/pt-br/footer-1.yml, _data/lang/ru/footer-1.yml, _data/lang/tr/footer-1.yml, _data/lang/zh-cn/footer-1.yml, _data/lang/zh-tw/footer-1.yml
=> footer-1.yml: remove link to Kovri

_data/merchants.yml
=> Add AUGET to the list of merchants

_posts/2020-08-22-triptych.md
Blog post announcing Triptych's acceptance for presentation and publication.
=> Triptych blog post

_i18n/en.yml, resources/user-guides/index.md
=> User Guides: Add external link to the 'Guide for the Monero GUI wallet'

resources/developer-guides/wallet-rpc.md
Co-authored-by: woodser <woodser@protonmail.com>
=> Add entry for "generate_from_keys".

_data/merchants.yml
~~Based on #1131 (review only aa85a6b)~~
- Cockbox (close #1137)
- Xchange.me (close #1139)
- DV Chain (close #1147)
- Newton (close #1148)
- CryptoWoo (close #1156)
=> Add 5 new merchants to the Merchants page

_i18n/en.yml, get-started/faq/index.md
=> FAQ: add 'Can I manually import the blockchain?'

_posts/2020-09-01-note-scheduled-upgrades.md
Posted in place of @dEBRUYNE-1. Posting my review below.
=> Blog: add post 'A note on scheduled protocol upgrades'

_i18n/en.yml
Hello everyone, 
Fixed missing capitalized 'M' for starting sentence in en.yml file. 
Thank you.
=> Fixed en.yml getcoins_para file, 'M' capitalized

_i18n/en.yml
Hello everyone, 
I suggest changing the word "is" for the word " has" in line-250 from the en.yml file. This to give a better contextualization to the text. Just read it with "is" and let me know your comments. 
Thank you.
:)
=> Suggest changes in en.yml (#1177 added to this PR)

_i18n/en.yml, _includes/header.html, blog/index.html, community/hangouts/index.md, community/sponsorships/index.md, community/team/index.md, css/custom.css, downloads/index.md, get-started/faq/index.md, index.html
I reviewed the entire website to assess its accessibility status. It's in a good condition overall and i haven't found any critical problems. I made some improvements that will improve the UX of visually impaired users. I couldn't implement some changes because they would have required javascript (video controls and tabs scrolling). Would be great if somebody with more experience about accessibility could review this PR, so to give suggestions on how to improve the website further.
- Fixed some interactive elemets which weren't focusable (using 'tabindex')
- Label interactive elements which weren't labelled
- Slightly increase contrast of the grey text in the top navigation bars to reach level AA in the [WCAG](https://www.w3.org/TR/WCAG20/) rating system and increse visibility of the text
=> Improve accessibility

_data/merchants.yml
=> Add XenPods to the list of merchants

_i18n/ru/resources/moneropedia/daemon.md
added russian translation for moneropedia "demon" entry:
- _i18n/ru/resources/moneropedia/daemon.md
ping to review: @LvMsterfild @monerorus @erciccione
=> Update Moneropedia "demon" entry (Russian translate)

_i18n/en.yml, _includes/upgrade.html, _layouts/index.html, css/custom.css
I changed a bit the structure and added useful links. ~~Now the banner appears on all pages, not only the home.~~
=> Add banner for October 2020 network upgrade

_data/merchants.yml
=> Add 'LyraHosting' to the list of merchants

_data/downloads.yml
=> Downloads: Add link to source code for CLI (mobile)

index.html
Add missing slash for:
- merchants
- library
=> Add missing slash (index.html)

_posts/2020-10-05-monero-GUI-0.17.0.1-released.md
=> blog: fix typo

_data/merchants.yml
Hi, Incognito has a new landing page for the DEX, I've changed the merchants with the actual link. :)
=> Merchants: Update Incognito website link

_includes/head.html
SVGs are not supported by opengraph.
=> head.html: show monero logo in og:image if page.image is an SVG file

_i18n/en.yml, resources/user-guides/index.md
Closes #909
~~Based on #1154 (review only 50f77a3 )~~
=> Add guide 'Set up a wallet (using a remote node) on Tails' (external onion address)

_i18n/ar/resources/moneropedia/ring-size.md, _i18n/de/resources/moneropedia/ring-size.md, _i18n/en/resources/moneropedia/ring-size.md, _i18n/es/resources/moneropedia/ring-size.md, _i18n/fr/resources/moneropedia/ring-size.md, _i18n/it/resources/moneropedia/ring-size.md, _i18n/nl/resources/moneropedia/ring-size.md, _i18n/pl/resources/moneropedia/ring-size.md, _i18n/pt-br/resources/moneropedia/ring-size.md, _i18n/ru/resources/moneropedia/ring-size.md, _i18n/tr/resources/moneropedia/ring-size.md, _i18n/zh-cn/resources/moneropedia/ring-size.md, _i18n/zh-tw/resources/moneropedia/ring-size.md
~~Based on #1136 (review only ac6445e)~~
=> Moneropedia: update entry 'Ring Size'

_data/merchants.yml
According to a report, deposits don't get credited: https://www.reddit.com/r/Monero/comments/j5s0jx/avoid_monerocardgamescom/
=> Merchants: remove 'monerocardgames.com'

_data/merchants.yml
=> Add 'Crypto Cove' to the list of merchants

_data/merchants.yml
=> Add 'Codify Global' to the list of merchants

_data/merchants.yml
=> Add 'Bitgear Australia' to the list of merchants

_data/merchants.yml
=> Remove 'Hosting Canada' ftom the list of merchants

_data/merchants.yml
=> Add 'ClientVPS' to the list of merchants

_i18n/en.yml
I mistakenly removed it with 125a168495e34baec447f8cacabe9c7d96f74e98
=> Contributing: fix missing part about ccs

_data/merchants.yml
=> Add 'Symbolika' to the list of merchants

_data/merchants.yml
=> Add 'Miller Technical Services' to the list of merchants

_data/merchants.yml
=> Remove ' VPNtesting' ftom the list of merchants

_data/merchants.yml
=> Remove 'Indacoin' ftom the list of merchants

_i18n/de/resources/moneropedia/paperwallet.md, _i18n/de/resources/moneropedia/paymentid.md, _i18n/de/resources/moneropedia/pedersen-commitment.md, _i18n/de/resources/moneropedia/pruning.md
- Paper Wallet
- Payment ID
- Pedersen Commitment
- Pruning
=> German translation of Moneropedia entries starting with P

_i18n/de/resources/moneropedia/randomx.md, _i18n/de/resources/moneropedia/remote-node.md, _i18n/de/resources/moneropedia/ring-size.md, _i18n/de/resources/moneropedia/ringCT.md, _i18n/de/resources/moneropedia/ringsignatures.md
- RandomX
- Remote Node
- Ring Size
- Ring CT
- Ring Signature
=> German translation of Moneropedia entries starting with R

_i18n/de/resources/moneropedia/scalability.md, _i18n/de/resources/moneropedia/signature.md, _i18n/de/resources/moneropedia/smartmining.md, _i18n/de/resources/moneropedia/spendkey.md, _i18n/de/resources/moneropedia/stealthaddress.md
- Scalability
- Signature
- Smart Mining
- Spend Key
- Stealth Address
=> German translation of Moneropedia entries starting with S

_data/merchants.yml
=> Add 'Veldt Gold' to the list of merchants

resources/developer-guides/daemon-rpc.md
See https://github.com/monero-project/monero/issues/7029#issuecomment-732232037
=> daemon-rpc guide: Fix target_height value for sync_info

_data/merchants.yml
=> Add 'SphinxLogic' to the list of merchants

_data/merchants.yml
=> Add 'Backtestking' to the list of merchants

_i18n/ar/resources/moneropedia/clsag.md, _i18n/de/resources/moneropedia/clsag.md, _i18n/en.yml, _i18n/en/resources/moneropedia/clsag.md, _i18n/es/resources/moneropedia/clsag.md, _i18n/fr/resources/moneropedia/clsag.md, _i18n/it/resources/moneropedia/clsag.md, _i18n/nl/resources/moneropedia/clsag.md, _i18n/pl/resources/moneropedia/clsag.md, _i18n/pt-br/resources/moneropedia/clsag.md, _i18n/ru/resources/moneropedia/clsag.md, _i18n/tr/resources/moneropedia/clsag.md, _i18n/zh-cn/resources/moneropedia/clsag.md, _i18n/zh-tw/resources/moneropedia/clsag.md, resources/moneropedia/clsag.md
=> Add 'CLSAG' Moneropedia entry

_i18n/ar/resources/moneropedia/remote-node.md, _i18n/en/resources/moneropedia/remote-node.md, _i18n/es/resources/moneropedia/remote-node.md, _i18n/fr/resources/moneropedia/remote-node.md, _i18n/it/resources/moneropedia/remote-node.md, _i18n/nl/resources/moneropedia/remote-node.md, _i18n/pl/resources/moneropedia/remote-node.md, _i18n/pt-br/resources/moneropedia/remote-node.md, _i18n/tr/resources/moneropedia/remote-node.md, _i18n/zh-cn/resources/moneropedia/remote-node.md, _i18n/zh-tw/resources/moneropedia/remote-node.md
https://wikidiff.com/wich/which
=> fix: typo from wich to which

_data/merchants.yml
=> Add '1bit.group' to the list of merchants

_data/downloads.yml, downloads/index.md
and add clarifying comment on top of _data/downloads.yml
=> Downloads: Fix order of appeareance of platform-specific releases

_includes/footer.html
hi, just a small typo i found.
=> Typo on footer "Exchange"

_i18n/en.yml, _includes/footer.html
Requires #1260 (I added a link to the 'Workgroup' page that doesn't exist yet).
I moved some stuff around, added and removed some entries, added a link to the Sitemap, removed the IRC Section and replaced with a more generic 'Reach Out' section.
=> Footer: reorganize entries

_i18n/de/resources/moneropedia/kovri.md, _i18n/de/resources/moneropedia/locally-unique-host.md, _i18n/de/resources/moneropedia/mining.md, _i18n/de/resources/moneropedia/mnemonicseed.md, _i18n/de/resources/moneropedia/node.md, _i18n/de/resources/moneropedia/openalias.md
- Kovri
- Locally Unique Host
- Mining
- Mnemonic Seed
- Node
- OpenAlias
=> German translation of Moneropedia entries K - O

_i18n/en.yml
As suggested in https://github.com/monero-project/monero-site/pull/1260#discussion_r542885137 by @hyc
=> Corrections to new 'Workgroups' page

_i18n/de/resources/user-guides/Offline_Backup.md, _i18n/de/resources/user-guides/importing_blockchain.md, _i18n/de/resources/user-guides/monero_tools.md, _i18n/de/resources/user-guides/vps_run_node.md
- How to make an offline backup
- How to run a node on VPS
- Importing the Monero blockchain
- Monero Tools
=> German Translation of User Guides (General 1/2)

_i18n/de/resources/user-guides/howto_fix_stuck_funds.md, _i18n/de/resources/user-guides/mine-to-pool.md, _i18n/de/resources/user-guides/restore_account.md, _i18n/de/resources/user-guides/restore_from_keys.md, _i18n/de/resources/user-guides/solo_mine_GUI.md
- How to mine on a pool with XMRig
- How to solo mine with the GUI
- How to fix locked up funds
- How to restore your account
- Restoring wallet from keys
=> German Translation of User Guides (Mining, Recovery)

_i18n/en.yml
Small typo, grammar, style changes. Feel free to critique.
=> Minor fixes to workgroups

_i18n/de/resources/user-guides/node-i2p-zero.md, _i18n/de/resources/user-guides/securely_purchase.md, _i18n/de/resources/user-guides/verification-allos-advanced.md, _i18n/de/resources/user-guides/verification-windows-beginner.md
- Securely purchasing and storing Monero
- Verify binaries on Linux, Mac, or Windows command line (advanced)
- Verify binaries on Windows (beginner)
- Run a Monero node through I2P with I2P-zero
(Edit: I accidentally listed the wrong entries which is fixed now.)
=> German Translation of User Guides (General 2/2)

_i18n/de/resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md, _i18n/de/resources/user-guides/ledger-wallet-cli.md, _i18n/de/resources/user-guides/monero-wallet-cli.md, _i18n/de/resources/user-guides/prove-payment.md, _i18n/de/resources/user-guides/remote_node_gui.md, _i18n/de/resources/user-guides/view_only.md
- CLI wallet/daemon isolation wit Qubes + Whonix
- Getting started with the CLI wallet
- How to connect to a remote node within GUI wallet
- How to make a view-only wallet
- How to prove payment
- How to generate a Ledger Monero wallet with the CLI
=> German Translation of User Guides (Wallet 1/2)

_posts/2020-12-24-Bulletproofs+-in-Monero.md
Removes unnecessary quotation marks.
=> Minor format edit to Bulletproofs+ blog post

css/custom.css, resources/research-lab/index.md
It's basically already a button, let's make it properly.
=> MRL: make the 'read paper' link a button

_i18n/en.yml, get-started/faq/index.md
=> FAQ: add 'I haven't touched my Monero in a long time...'

index.html, media/subtitles/en/monero-promo.vtt
Subtitles provided by @staff91
More subtitles are likely to arrive soon, i'll look into improving the videos. The subtitles format is `.vtt`, which is not supported by weblate, so at least for now translations must be submitted to this repo.
I'm having weird results on chromium, but that could be related to my local setup. So please test on your browsers. [There shouldn't be compatibility issues](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track).
=> Add subtitles for the what-is-monero video in home

_i18n/en.yml, resources/roadmap/index.md
`info-block` needed to be added for the links to be displayed correctly.
=> Roadmap: add links to blog posts and Moneropedia

_i18n/en.yml, resources/developer-guides/index.md
=> Dev guides: add csharp-monero to 'libraries and helpers'

_data/merchants.yml
=> merchants: add actio-fast-pay.net

_includes/footer.html, css/custom.css
=> footer: add icon to feed

resources/roadmap/index.md
Updated roadmap page, added 2021
=> Updated roadmap page

_data/merchants.yml
=> Add 'IVPN' to the list of merchants

_includes/head.html
=> head: fix og links to include domain

_i18n/en.yml, get-started/contributing/index.md
More detailed and updated info, updated links, added button for CCS and made several cosmetic changes
=> Refresh 'Contributing' page

_data/merchants.yml
These 3 merchants aren't accepting monero as a payment method
=> Removed merchants that aren't accepting monero

_i18n/ar/resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md, _i18n/de/resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md, _i18n/es/resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md, _i18n/fr/resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md, _i18n/it/resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md, _i18n/nl/resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md, _i18n/pl/resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md, _i18n/pt-br/resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md, _i18n/ru/resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md, _i18n/tr/resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md, _i18n/zh-cn/resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md, _i18n/zh-tw/resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md
Part of #1270 (All user guides in all languages must have their structure standardized and fit the English version)
=> user guides: uniform structure of all cli_wallet_daemon_isolation_qubes_whonix.md

_i18n/ar/resources/user-guides/importing_blockchain.md, _i18n/de/resources/user-guides/importing_blockchain.md, _i18n/en/resources/user-guides/importing_blockchain.md, _i18n/es/resources/user-guides/importing_blockchain.md, _i18n/fr/resources/user-guides/importing_blockchain.md, _i18n/it/resources/user-guides/importing_blockchain.md, _i18n/nl/resources/user-guides/importing_blockchain.md, _i18n/pl/resources/user-guides/importing_blockchain.md, _i18n/pt-br/resources/user-guides/importing_blockchain.md, _i18n/ru/resources/user-guides/importing_blockchain.md, _i18n/tr/resources/user-guides/importing_blockchain.md, _i18n/zh-cn/resources/user-guides/importing_blockchain.md, _i18n/zh-tw/resources/user-guides/importing_blockchain.md
Part of #1270
- Remove author from the content of the guide
- Outdated translations were resetted (too time consuming to adapt them all and probably they will end up different anyway)
=> user guides: uniform structure of importing_blockchain.md for all languages

_i18n/ar/resources/user-guides/ledger-wallet-cli.md, _i18n/de/resources/user-guides/ledger-wallet-cli.md, _i18n/en/resources/user-guides/ledger-wallet-cli.md, _i18n/es/resources/user-guides/ledger-wallet-cli.md, _i18n/fr/resources/user-guides/ledger-wallet-cli.md, _i18n/it/resources/user-guides/ledger-wallet-cli.md, _i18n/nl/resources/user-guides/ledger-wallet-cli.md, _i18n/pl/resources/user-guides/ledger-wallet-cli.md, _i18n/pt-br/resources/user-guides/ledger-wallet-cli.md, _i18n/ru/resources/user-guides/ledger-wallet-cli.md, _i18n/tr/resources/user-guides/ledger-wallet-cli.md, _i18n/zh-cn/resources/user-guides/ledger-wallet-cli.md, _i18n/zh-tw/resources/user-guides/ledger-wallet-cli.md
and remove authors from the body of the guide
Part of #1270
=> user guides: uniform structure of leger-wallet-cli.md

_posts/2021-01-08-monero-0.17.1.9-released.md, _posts/2021-01-08-monero-GUI-0.17.1.9-released.md
=> Fix URL to hashes.txt (only the text, actual URL is OK) for releases 0.17.1.9

_i18n/en.yml, _layouts/user-guide.html
Somebody asked for this on reddit. Particularly useful for long documents.
=> Add 'Go to the top' button to user and dev guides

_layouts/blog_by_tag.html, blog/index.html, downloads/index.md
=> Add 'title' attribute to all 'arrow-up' buttons

_data/merchants.yml
:(
https://xmr.to/blog/job-done
=> merchants: remove xmr.to

README.md, _includes/footer.html, _includes/head.html, _includes/onion.html, css/custom.css, onion.txt
Requires #1452
Closes #904
~~`onion.txt` is just a draft, needs to be improved and signed.~~
=> Prepare repo for deployment of onion service 

_data/merchants.yml
Referencing issue: https://github.com/monero-project/monero-site/issues/1460
Added the URL and site description to `monero-site\_data\merchants.yml`.
=> [1460] Adding YogiWay data to merchants.yml

_data/merchants.yml
https://www.reddit.com/r/Monero/comments/lkg2ml/minko_has_closed/
=> Merchants: remove minko

_data/merchants.yml
=> merchants: remove flokinet

_data/merchants.yml
- Bacrypt.com (closes #1444)
- BuyVM / Frantech (closes #1462)
- CelticGold AG (closes #1449)
- pay2day.top (closes #1469)
- getblock (closes #1465)
=> Merchants: add 5 merchants

_plugins/moneropedia.rb
=> moneropedia.rb: replace hyperlink text with regex match

resources/developer-guides/daemon-rpc.md
https://github.com/monero-project/monero/pull/7112
To be merged when a release will include the change.
=> daemon-rpc: target_height is 0 if synced

_i18n/en.yml, get-started/what-is-monero/index.md
=> what is monero: update content and add relevant links

resources/roadmap/index.md
=> roadmap: onion address completed in feb 2021

_i18n/en.yml
https://github.com/monero-project/monero-site/pull/1496#discussion_r585397642
=> library: remove version from the 'Monero Addresses Cheatsheet'

_i18n/en.yml, downloads/index.md
=> downloads: add header 'Antivirus'

_i18n/en.yml
Removed obsolete reference to I2P. Semantics.
=> about: decentralization - revise and remove irrelevant content

_data/merchants.yml, community/merchants/index.md, css/custom.css
Applies the responsive design used by the blog and downloads page.
=> merchants: add scroll-to-top button & mobile dropdown menu

_data/merchants.yml
I received a detailed complaint about this company, from somebody who lost money using their website. They do seem to be scammers. Removing them from the list.
It was added with #1388.
closes #1517
=> merchants: remove actio-fast-pay.net

_data/merchants.yml
We received multiple complaints about this exchange. Removing it from the list of Merchants.
https://old.reddit.com/r/Monero/comments/kt2bgy/dispute_regarding_1bitgroup_and_issue_on/
https://old.reddit.com/r/Monero/comments/m0066o/scammed_by_1bitgroup/
Was added with https://github.com/monero-project/monero-site/issues/1349
=> merchants: remove 1bit

index.html, media/subtitles/it/monero-promo.vtt
Recovering #1386 (with my suggestions implemented)
=> Add Italian subtitles for the promo video in the home

_data/chats.yml
=> hangouts: change domain of matrix rooms to monero.social

_i18n/en.yml, get-started/what-is-monero/index.md
Requires #1481
Adding some action buttons as suggested in #1484 and removing redundant header.
=> what is monero: add action buttons and remove redundant header

_i18n/en.yml
slightly edited wording and highlight some text in bold
=> merchants: further clarify that we don't do any vetting of the merchants

_i18n/en.yml, library/index.md
=> library: add cheatsheets section

_data/merchants.yml
- 1984 Hosting Iceland (closes #1512)
- CoinCat (closes #1516)
- TrilightZone (closes #1520)
=> Merchants: add 3 new merchants

_i18n/ar/resources/user-guides/weblate/solo_mine_GUI.po, _i18n/ar/resources/user-guides/weblate/tor_wallet.po, _i18n/de/resources/user-guides/weblate/solo_mine_GUI.po, _i18n/de/resources/user-guides/weblate/tor_wallet.po, _i18n/en/resources/user-guides/weblate/solo_mine_GUI.pot, _i18n/en/resources/user-guides/weblate/tor_wallet.pot, _i18n/es/resources/user-guides/weblate/solo_mine_GUI.po, _i18n/es/resources/user-guides/weblate/tor_wallet.po, _i18n/fr/resources/user-guides/weblate/solo_mine_GUI.po, _i18n/fr/resources/user-guides/weblate/tor_wallet.po, _i18n/it/resources/user-guides/weblate/solo_mine_GUI.po, _i18n/it/resources/user-guides/weblate/tor_wallet.po, _i18n/nb-no/resources/user-guides/weblate/solo_mine_GUI.po, _i18n/nb-no/resources/user-guides/weblate/tor_wallet.po, _i18n/nl/resources/user-guides/weblate/solo_mine_GUI.po, _i18n/nl/resources/user-guides/weblate/tor_wallet.po, _i18n/pl/resources/user-guides/weblate/solo_mine_GUI.po, _i18n/pl/resources/user-guides/weblate/tor_wallet.po, _i18n/pt-br/resources/user-guides/weblate/solo_mine_GUI.po, _i18n/pt-br/resources/user-guides/weblate/tor_wallet.po, _i18n/ru/resources/user-guides/weblate/solo_mine_GUI.po, _i18n/ru/resources/user-guides/weblate/tor_wallet.po, _i18n/tr/resources/user-guides/weblate/solo_mine_GUI.po, _i18n/tr/resources/user-guides/weblate/tor_wallet.po, _i18n/zh-cn/resources/user-guides/weblate/solo_mine_GUI.po, _i18n/zh-cn/resources/user-guides/weblate/tor_wallet.po, _i18n/zh-tw/resources/user-guides/weblate/solo_mine_GUI.po, _i18n/zh-tw/resources/user-guides/weblate/tor_wallet.po
fifth batch of gettextized user guides (fourth batch: #1538)
Gettextized:
- solo_mine_GUI.md
- tor_wallet.md
Part of #1270
=> Gettextize solo_mine_GUI.md and tor_wallet.md

downloads/index.md, resources/roadmap/index.md
I moved kastelo to the future section and changed into "upcoming".
It seems there's no development for it: 
https://github.com/monero-project/kastelo/commits/master
=> Roadmap Kastelo Update

resources/developer-guides/index.md
=> developer guides: fix card alignment

css/custom.css
=> custom.css: fix languages menu overlap

community/hangouts/index.md
=> hangouts: properly rearrange buttons

index.html
=> home: align moneropedia card

get-started/faq/index.md
Official documentation should be first.
=> faq: change resources order

downloads/index.md
=> downloads: fix closing div for cli section

css/custom.css
Examples of this ugliness:
https://www.getmonero.org/resources/user-guides/mine-to-pool.html
https://www.getmonero.org/get-started/accepting/
=> custom.css: style ordered lists

_data/merchants.yml
- 24bestex (closes #1510)
- cryptoFacile (closes #1587)
- North of Boston (closes #1545)
- Declic CBD (closes #1577)
- Bitvape (#1584)
- Fork Networking (closes #1290)
- pandaCD (closes #1597)
- ProxyStore (closes #1601)
- Z1 Fashion- Imagoza (#1602)
- Vesper Farms (#1603)
- Reflectacles Privacy Eyewear (#1604)
- Southwest Environmental Limited (#1608)
=> add 12 new merchants

_i18n/en.yml
=> MRL: add acronym to title and rename papers section

_data/merchants.yml
=> merchants: remove coinexwo

_i18n/en.yml
=> home: fix typo hundred -> hundreds

_data/chats.yml, _data/merchants.yml, _i18n/en.yml
The chat seems to be unmaintained.
=> remove mentions of #monero-otc

_layouts/blog_by_tag.html, css/custom.css
Main improvements can be seen here:
https://www.getmonero.org/blog/tags/releases.html
https://www.getmonero.org/resources/research-lab/
=> Add more responsiveness to mobile views

_i18n/en/resources/user-guides/monero-wallet-cli.md
Closes #1593
- updated content
- updated structure for consistency with the other guides
=> user guides: update monero-wallet-cli.md

_data/merchants.yml
=> merchants: remove evolution host

_data/merchants.yml
=> merchants: remove enter-change

_i18n/en.yml, css/custom.css, index.html
closes #1483
closes #1503
Preview desktop:
Preview mobile:
=> home: update top card with new slogan and additional button

_data/merchants.yml
=> merchants: remove newton.co

.github/ISSUE_TEMPLATE/remove-merchant.md, README.md
People started to use the "New Merchant" template to signal they want to remove a merchant, so i created a dedicated template and updated the README.
=> Add issue template for removing a merchant and update README

_i18n/en.yml, css/custom.css, get-started/mining/index.md, img/emojis/274C.svg
closes #1315 
closes #1615 
closes #1585
preview (it's basically the same on mobile):
=> revamp 'mining' page

_includes/footer.html, _includes/header.html
by specifying the size of images in header and footer
=> optimize cumulative layout shift in the home

_data/merchants.yml
=> merchants: remove 24bestex

_i18n/en.yml, blog/index.html, css/custom.css
Recovers #1575 (with some minor changes) and makes 'Next' and 'Prev' translatable.
=> Minor fixes and adjustements to 'Blog'

_data/merchants.yml
=> merchants: remove coincat.in

_i18n/en/resources/user-guides/monero-wallet-cli.md
I elaborated a bit about the labels for new subaddresses. Provided an example.
=> monero-wallet-cli.md: added guidance on labeling

_data/merchants.yml
I have added Occidental Technologies to the Merchant list, it was OK'd and the "needs investigation" status was removed.
=> Add Occidental Technologies to the list of Merchants

css/custom.css
=> custom.css: add right and left padding on orange button

_i18n/en.yml, community/hangouts/index.md
This is the less invasive way to fix the 2 boxes at mismatching heights.
=> hangouts: add string to 'workgroup resources'

css/custom.css, img/emojis/1F310.svg, img/emojis/1F4C4.svg
=> replace unicode icons with svgs in developer-guides page

downloads/index.md
=> downloads: decrease width of "download blockchain" button

_i18n/en.yml, downloads/index.md
Changes:
- Separate mobile/light wallets in two categories:
- Local sync wallets: don't share any key with a remote server.
- Remote sync (lightweight) wallets: share the private view key with a third-party server.
=> Downloads: differentiate local sync x remote sync (lightweight) wallets

resources/roadmap/index.md
Announcement: https://www.getmonero.org/2021/08/20/atomic-swaps.html
=> roadmap: change 'atomic swaps' to completed

css/custom.css
=> css: change line-height of code blocks to 1.4

README.md
- Add a table of contents, like monero and monero-gui repositories use. 
- Remove "Introduction" title
- Some fixes to the introduction text
=> README: fix introduction text

_i18n/en.yml, get-started/faq/index.md
=> faq: add entry 'What is Monero's maximum supply?'

_i18n/ar/resources/user-guides/restore_account.md, _i18n/ar/resources/user-guides/weblate/restore_account.po, _i18n/de/resources/user-guides/restore_account.md, _i18n/de/resources/user-guides/weblate/restore_account.po, _i18n/en/resources/user-guides/restore_account.md, _i18n/en/resources/user-guides/weblate/restore_account.pot, _i18n/es/resources/user-guides/restore_account.md, _i18n/es/resources/user-guides/weblate/restore_account.po, _i18n/fr/resources/user-guides/restore_account.md, _i18n/fr/resources/user-guides/weblate/restore_account.po, _i18n/it/resources/user-guides/restore_account.md, _i18n/it/resources/user-guides/weblate/restore_account.po, _i18n/nb-no/resources/user-guides/restore_account.md, _i18n/nb-no/resources/user-guides/weblate/restore_account.po, _i18n/nl/resources/user-guides/restore_account.md, _i18n/nl/resources/user-guides/weblate/restore_account.po, _i18n/pl/resources/user-guides/restore_account.md, _i18n/pl/resources/user-guides/weblate/restore_account.po, _i18n/pt-br/resources/user-guides/restore_account.md, _i18n/pt-br/resources/user-guides/weblate/restore_account.po, _i18n/ru/resources/user-guides/restore_account.md, _i18n/ru/resources/user-guides/weblate/restore_account.po, _i18n/tr/resources/user-guides/restore_account.md, _i18n/tr/resources/user-guides/weblate/restore_account.po, _i18n/zh-cn/resources/user-guides/restore_account.md, _i18n/zh-cn/resources/user-guides/weblate/restore_account.po, _i18n/zh-tw/resources/user-guides/restore_account.md, _i18n/zh-tw/resources/user-guides/weblate/restore_account.po, po/user-guides/restore_account.config
Guide changed with  #1781.
We also add a dedicated `.config` file for the guide.
=> user guides: Update all language files after updates to restore_account.md (#1781)

_i18n/ar/resources/moneropedia/daemon.md, _i18n/ar/resources/moneropedia/weblate/daemon.po, _i18n/de/resources/moneropedia/daemon.md, _i18n/de/resources/moneropedia/weblate/daemon.po, _i18n/en/resources/moneropedia/daemon.md, _i18n/en/resources/moneropedia/weblate/daemon.pot, _i18n/es/resources/moneropedia/daemon.md, _i18n/es/resources/moneropedia/weblate/daemon.po, _i18n/fr/resources/moneropedia/daemon.md, _i18n/fr/resources/moneropedia/weblate/daemon.po, _i18n/it/resources/moneropedia/daemon.md, _i18n/it/resources/moneropedia/weblate/daemon.po, _i18n/nb-no/resources/moneropedia/daemon.md, _i18n/nb-no/resources/moneropedia/weblate/daemon.po, _i18n/nl/resources/moneropedia/daemon.md, _i18n/nl/resources/moneropedia/weblate/daemon.po, _i18n/pl/resources/moneropedia/daemon.md, _i18n/pl/resources/moneropedia/weblate/daemon.po, _i18n/pt-br/resources/moneropedia/daemon.md, _i18n/pt-br/resources/moneropedia/weblate/daemon.po, _i18n/ru/resources/moneropedia/daemon.md, _i18n/ru/resources/moneropedia/weblate/daemon.po, _i18n/tr/resources/moneropedia/daemon.md, _i18n/tr/resources/moneropedia/weblate/daemon.po, _i18n/zh-cn/resources/moneropedia/daemon.md, _i18n/zh-cn/resources/moneropedia/weblate/daemon.po, _i18n/zh-tw/resources/moneropedia/daemon.md, _i18n/zh-tw/resources/moneropedia/weblate/daemon.po, po/moneropedia/daemon.config
=> moneropedia: localization system for daemon.md

_posts/2021-10-05-p2pool-released.md
P2Pool binaries have been released here: 
https://github.com/SChernykh/p2pool/releases/tag/v1.0
Source: 
https://github.com/SChernykh/p2pool
=> Add blog post for p2pool release

_i18n/ar/resources/moneropedia/ring-size.md, _i18n/ar/resources/moneropedia/weblate/ring-size.po, _i18n/de/resources/moneropedia/ring-size.md, _i18n/de/resources/moneropedia/weblate/ring-size.po, _i18n/en/resources/moneropedia/ring-size.md, _i18n/en/resources/moneropedia/weblate/ring-size.pot, _i18n/es/resources/moneropedia/ring-size.md, _i18n/es/resources/moneropedia/weblate/ring-size.po, _i18n/fr/resources/moneropedia/ring-size.md, _i18n/fr/resources/moneropedia/weblate/ring-size.po, _i18n/it/resources/moneropedia/ring-size.md, _i18n/it/resources/moneropedia/weblate/ring-size.po, _i18n/nb-no/resources/moneropedia/ring-size.md, _i18n/nb-no/resources/moneropedia/weblate/ring-size.po, _i18n/nl/resources/moneropedia/ring-size.md, _i18n/nl/resources/moneropedia/weblate/ring-size.po, _i18n/pl/resources/moneropedia/ring-size.md, _i18n/pl/resources/moneropedia/weblate/ring-size.po, _i18n/pt-br/resources/moneropedia/ring-size.md, _i18n/pt-br/resources/moneropedia/weblate/ring-size.po, _i18n/ru/resources/moneropedia/ring-size.md, _i18n/ru/resources/moneropedia/weblate/ring-size.po, _i18n/tr/resources/moneropedia/ring-size.md, _i18n/tr/resources/moneropedia/weblate/ring-size.po, _i18n/zh-cn/resources/moneropedia/ring-size.md, _i18n/zh-cn/resources/moneropedia/weblate/ring-size.po, _i18n/zh-tw/resources/moneropedia/ring-size.md, _i18n/zh-tw/resources/moneropedia/weblate/ring-size.po, po/moneropedia/ring-size.config
=> moneropedia: localization system for ring-size.md

_i18n/ar/resources/moneropedia/scalability.md, _i18n/ar/resources/moneropedia/weblate/scalability.po, _i18n/de/resources/moneropedia/scalability.md, _i18n/de/resources/moneropedia/weblate/scalability.po, _i18n/en/resources/moneropedia/scalability.md, _i18n/en/resources/moneropedia/weblate/scalability.pot, _i18n/es/resources/moneropedia/scalability.md, _i18n/es/resources/moneropedia/weblate/scalability.po, _i18n/fr/resources/moneropedia/scalability.md, _i18n/fr/resources/moneropedia/weblate/scalability.po, _i18n/it/resources/moneropedia/scalability.md, _i18n/it/resources/moneropedia/weblate/scalability.po, _i18n/nb-no/resources/moneropedia/scalability.md, _i18n/nb-no/resources/moneropedia/weblate/scalability.po, _i18n/nl/resources/moneropedia/scalability.md, _i18n/nl/resources/moneropedia/weblate/scalability.po, _i18n/pl/resources/moneropedia/scalability.md, _i18n/pl/resources/moneropedia/weblate/scalability.po, _i18n/pt-br/resources/moneropedia/scalability.md, _i18n/pt-br/resources/moneropedia/weblate/scalability.po, _i18n/ru/resources/moneropedia/scalability.md, _i18n/ru/resources/moneropedia/weblate/scalability.po, _i18n/tr/resources/moneropedia/scalability.md, _i18n/tr/resources/moneropedia/weblate/scalability.po, _i18n/zh-cn/resources/moneropedia/scalability.md, _i18n/zh-cn/resources/moneropedia/weblate/scalability.po, _i18n/zh-tw/resources/moneropedia/scalability.md, _i18n/zh-tw/resources/moneropedia/weblate/scalability.po, po/moneropedia/scalability.config
=> moneropedia: localization system for scalability.md

_posts/2021-12-22-what-is-seraphis.md
I wrote this post on u/dEBRUYNE's request. Let me know if I should add/clarify anything.
Before anyone whines about my mention of MobileCoin, you should keep in mind I wrote the first draft of the Seraphis paper while an employee at MobileCoin.
=> blog post: What is Seraphis, and Why Should You Care?

_i18n/en.yml, get-started/mining/index.md
When the Moneropedia entry will be ready (#1845) we can also add links to that entry.
=> mining: add section dedicated to p2pool

community/sponsorships/index.md
Globee, for their own reasons, unrelated to Monero, is no longer sponsoring Monero's infrastructure.
=> sponsors: remove globee

_i18n/en.yml
While reading through the site I came across a paragraph that felt clunky. I re-wrote it to be a little more clear. I'm not sure the proper way of going about fixing this for all other languages.
=> Rephrased awkward paragraph

resources/developer-guides/wallet-rpc.md
=> developer-guides: fix incorrect input in wallet rpc

_posts/2021-06-24-general-fund-2020-2021-report.md
=> fix link to key images in general fund report (2020-2021)

_i18n/en.yml
mentioning libera instead of freenode for #monero-space and #monero-policy
=> update reference from freenode to libera

_i18n/en.yml, community/sponsorships/index.md
As proposed in https://github.com/monero-project/monero-site/pull/1888
=> sponsorships: add section with past sponsors

_posts/2021-04-24-this-year-in-monero.md
This is a simple update to the blog post to update the author name (now sethforprivacy) and update all blog URLs to the proper domain of sethforprivacy.com.
=> Update "This Year in Monero 2021" URLs and author

community/workgroups/index.md
=> workgroups: fix link

get-started/mining/index.md
=> mining: fix stray </a>

downloads/index.md
added (target="_blank") in some <a> links to open in another page.
=> open links in another page

_posts/2022-04-29-monero-0.17.3.2-released.md
The script thought the username is a pull request.
=> blog: fix incorrect link

_i18n/en.yml
Fixes broken link issue [1944](https://github.com/monero-project/monero-site/issues/1944)
=> fix get-started/mining/ announcement post link 404

_i18n/en.yml
small fix for https://www.getmonero.org/get-started/contributing/ button
=> go the the ccs -> go to the ccs

.github/workflows/hashes.yaml
Closes #1576 
[Help for reviewer](https://github.com/plowsof/validate-sources)
=> verify source integrity in workflows

_i18n/en.yml
=> fix matrix link for -pools

.github/workflows/hashes.yaml, _data/downloads.yml, downloads/index.md
https://downloads.getmonero.org/cli/macarm8 redirect has to be created.
=> downloads: add macOS ARM link

resources/tools/index.md
Closes #1980
- changed link for nownodes
- removed backtestking
- removed monerobase
- removed vigla
=> tools: fixed 4 broken links (removed 3)

downloads/index.md
This reverts commit 22f72b05de8d78d2c9c2a614769da25033e246d8.
To be merged after Mymonero and edge will be confirmed on the correct network.
Edge: https://twitter.com/EdgeWallet/status/1563584457361149952
i'm unsure about the current status of Mymonero. Ping @LivBoss @AslanPonies
=> Revert "downloads: hide remote sync section until wallets upgrade to v16

downloads/hashes.txt
Fixes monero-project/monero#8581
=> Fix typo in filename in hashes.txt

.github/workflows/hashes.yaml
added "workflows:" to commit title and removed typo from comments
=> validate filenames in hashes.txt

resources/tools/index.md
=> remove moneroaddress.org from tools page

get-started/contributing/index.md, resources/user-guides/index.md
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256
http://xmrguide42y34onq.onion
http://xmrguide25ibknxgaray5rqksrclddxqku3ggdcnzg4ogdi5qkdkd2yd.onion
https://xmrguide.org
-----BEGIN PGP SIGNATURE-----
iQIzBAEBCAAdFiEExavlwOUPorPxSrktHK3Sf0H0XDwFAmDNV2gACgkQHK3Sf0H0
XDyDcA/+Ml29baAcZAvizv2N97R8LuofmSENDRkHpO/V80cEFLD6o+uUFQn99t0A
fxEilrZHGbddPPZHknqGu9loS/DuBg32DQRxqR7EPouVssfcUEpL5TrFG8xSVQcc
DoKB90padqHyU3Z3lVYO4lR6vd5UgkIEaf8B0E4DnKA8lbXY74Bha6ZcnHre6Xie
D/zz4pYIDfcVKc2XX/QtZP2ZezSJ0xcb8LEiFlzF4k05UWeWqz2SNWuKQN+1kxUJ
0O7qTXGj2qFGSYARKokFk0fmGxaJaXGSGHzv/aqP/EKHSKJMYHNHWx4vYV/MAhtg
Mo6PB4d78UyzsxbozynNybZnVAXQjOpb5gZrfJHcDl9muu1M4yldnKlig3fenLKe
KIuKzO+ITRtUGKMH8W6k1WZ8w4J65ZBDfdie0vxprBwEEKgAoDgNndPPDhrbx0Nc
18Gi6G/a928lLBuBLpn/sIEWfS8cI+0XHvCgdO6QIF6pKt16aiyKmDI5F7kgLgt0 …
```
=> fix xmrguide.org's onion links

_i18n/ar/resources/moneropedia/ring-size.md, _i18n/ar/resources/moneropedia/weblate/ring-size.po, _i18n/de/resources/moneropedia/ring-size.md, _i18n/de/resources/moneropedia/weblate/ring-size.po, _i18n/en/resources/moneropedia/ring-size.md, _i18n/en/resources/moneropedia/weblate/ring-size.pot, _i18n/es/resources/moneropedia/ring-size.md, _i18n/es/resources/moneropedia/weblate/ring-size.po, _i18n/fr/resources/moneropedia/ring-size.md, _i18n/fr/resources/moneropedia/weblate/ring-size.po, _i18n/it/resources/moneropedia/ring-size.md, _i18n/it/resources/moneropedia/weblate/ring-size.po, _i18n/nb-no/resources/moneropedia/ring-size.md, _i18n/nb-no/resources/moneropedia/weblate/ring-size.po, _i18n/nl/resources/moneropedia/ring-size.md, _i18n/nl/resources/moneropedia/weblate/ring-size.po, _i18n/pl/resources/moneropedia/ring-size.md, _i18n/pl/resources/moneropedia/weblate/ring-size.po, _i18n/pt-br/resources/moneropedia/ring-size.md, _i18n/pt-br/resources/moneropedia/weblate/ring-size.po, _i18n/ru/resources/moneropedia/ring-size.md, _i18n/ru/resources/moneropedia/weblate/ring-size.po, _i18n/tr/resources/moneropedia/ring-size.md, _i18n/tr/resources/moneropedia/weblate/ring-size.po, _i18n/zh-cn/resources/moneropedia/ring-size.md, _i18n/zh-cn/resources/moneropedia/weblate/ring-size.po, _i18n/zh-tw/resources/moneropedia/ring-size.md, _i18n/zh-tw/resources/moneropedia/weblate/ring-size.po
=> moneropedia: ringsize 11 -> 16 po/pot/md

_data/chats.yml
closes #2095 
link monero research lounge instead of main channel?
=> hangouts: fix matrix room links

resources/tools/index.md
closes #2105 
closes #2106 
removed swirlpay / added monerotech
jump to tools page: https://deploy-preview-2107--barolo-time-757cf9.netlify.app/resources/tools/
=> tools: remove swirlpay / add monerotech

_i18n/en.yml, resources/roadmap/index.md
+ Jamtis / Seraphis wiki link
note: i've noticed a little error of "checked" being added twice.. can edit that for the 2023 bump
=> roadmap: add seraphis/jamtis wiki link

README.md
=> Fix: typos in README.md

_i18n/ar/resources/user-guides/restore_account.md, _i18n/ar/resources/user-guides/weblate/restore_account.po, _i18n/de/resources/user-guides/restore_account.md, _i18n/de/resources/user-guides/weblate/restore_account.po, _i18n/en/resources/user-guides/restore_account.md, _i18n/en/resources/user-guides/weblate/restore_account.pot, _i18n/es/resources/user-guides/restore_account.md, _i18n/es/resources/user-guides/weblate/restore_account.po, _i18n/fr/resources/user-guides/restore_account.md, _i18n/fr/resources/user-guides/weblate/restore_account.po, _i18n/it/resources/user-guides/restore_account.md, _i18n/it/resources/user-guides/weblate/restore_account.po, _i18n/nb-no/resources/user-guides/restore_account.md, _i18n/nb-no/resources/user-guides/weblate/restore_account.po, _i18n/nl/resources/user-guides/restore_account.md, _i18n/nl/resources/user-guides/weblate/restore_account.po, _i18n/pl/resources/user-guides/restore_account.md, _i18n/pl/resources/user-guides/weblate/restore_account.po, _i18n/pt-br/resources/user-guides/restore_account.md, _i18n/pt-br/resources/user-guides/weblate/restore_account.po, _i18n/ru/resources/user-guides/restore_account.md, _i18n/ru/resources/user-guides/weblate/restore_account.po, _i18n/tr/resources/user-guides/restore_account.md, _i18n/tr/resources/user-guides/weblate/restore_account.po, _i18n/zh-cn/resources/user-guides/restore_account.md, _i18n/zh-cn/resources/user-guides/weblate/restore_account.po, _i18n/zh-tw/resources/user-guides/restore_account.md, _i18n/zh-tw/resources/user-guides/weblate/restore_account.po
user eud mistakenly [entered a wallet password for seed offset](https://libera.monerologs.net/monero-community/20221130#c169563) because the guide doesnt mention it 
```
4) Next, you will be asked to enter a seed offset passphrase if you have one
(this is NOT your wallet password).
```
This guide is not translated so we can make major changes to it if something else is wrong.
closes #918
=> user-guides: add seed offset to cli account restore

_posts/2023-01-01-seraphis-jamtis-developer-opportunities.md
Text original with some background info and discussion is [here](https://github.com/seraphis-migration/wallet3/issues/40) on the Seraphis workgroup project site.
The first two chapters contain info that of course can be found easily on the getmonero.org website, but the text is designed as self-contained and tries to address devs that don't know yet about Monero "in one go".
=> blog: Developer Opportunities at the Monero Project

.github/workflows/ci.yml
- upgrade ubuntu version to ubuntu-22.04
- upgrade to checkout@v3
- upgrade bundler version to 2.2.23
=> workflow: update ci.yml

_i18n/en/resources/user-guides/verification-allos-advanced.md
=> user-guides: fix toc for verification guide

_i18n/en.yml
=> correct text of global variable 'outdated'

_data/tags.yml
=> tags: add missing for seraphis blog

community/merchants/index.md
closes #2099 
no response for a while / still offline
=> merchants: remove morphtoken

_i18n/ar/resources/user-guides/change-restore-height.md, _i18n/ar/resources/user-guides/weblate/change-restore-height.po, _i18n/de/resources/user-guides/change-restore-height.md, _i18n/de/resources/user-guides/weblate/change-restore-height.po, _i18n/en/resources/user-guides/weblate/change-restore-height.pot, _i18n/es/resources/user-guides/change-restore-height.md, _i18n/es/resources/user-guides/weblate/change-restore-height.po, _i18n/fr/resources/user-guides/change-restore-height.md, _i18n/fr/resources/user-guides/weblate/change-restore-height.po, _i18n/it/resources/user-guides/change-restore-height.md, _i18n/it/resources/user-guides/weblate/change-restore-height.po, _i18n/nb-no/resources/user-guides/change-restore-height.md, _i18n/nb-no/resources/user-guides/weblate/change-restore-height.po, _i18n/nl/resources/user-guides/change-restore-height.md, _i18n/nl/resources/user-guides/weblate/change-restore-height.po, _i18n/pl/resources/user-guides/change-restore-height.md, _i18n/pl/resources/user-guides/weblate/change-restore-height.po, _i18n/pt-br/resources/user-guides/change-restore-height.md, _i18n/pt-br/resources/user-guides/weblate/change-restore-height.po, _i18n/ru/resources/user-guides/change-restore-height.md, _i18n/ru/resources/user-guides/weblate/change-restore-height.po, _i18n/tr/resources/user-guides/change-restore-height.md, _i18n/tr/resources/user-guides/weblate/change-restore-height.po, _i18n/zh-cn/resources/user-guides/change-restore-height.md, _i18n/zh-cn/resources/user-guides/weblate/change-restore-height.po, _i18n/zh-tw/resources/user-guides/change-restore-height.md, _i18n/zh-tw/resources/user-guides/weblate/change-restore-height.po, po/user-guides/change-restore-height.config
=> userguides: po/pot files for change-restore-height.md

community/sponsorships/index.md
more details? suggestions welcome
=> sponsorships: add disclaimer

po/po-update.sh
=> add moneropedia to po script

community/hangouts/index.md
charuto raised this suggestion, great idea and the space is actively maintained
=> hangouts: link matrix to the monerospace

_data/chats.yml
=> hangouts: update matrix links

downloads/index.md
Linux: https://github.com/cake-tech/cake_wallet/releases
MacOS: https://apps.apple.com/us/app/cake-wallet-for-xmr-monero/id1334702542
=> Add Linux and MacOS to Cake Wallet

_i18n/en.yml, get-started/faq/index.md
As suggested by @apertamono in #2006
Closes #2006
=> faq: change categories

resources/developer-guides/daemon-rpc.md
=> devguides: add add_aux_pow to daemon rpc

404.html, css/custom.css
=> fix button in 404 page too close to bottom in small screens

community/merchants/index.md
=> acceptedhere.io domain has expired

community/merchants/index.md
I wasn't sure whether to put BitcoinVN under "CEXes" or "Swappers", because it kinda fits both categories.
You can buy and sell XMR for the local currency VND, or any other supported cryptocurrency.
=> Add BitcoinVN

README.md
=> readme: fix small typos and improve grammar

_i18n/de.yml, _i18n/en.yml, _i18n/es.yml, _i18n/fr.yml, _i18n/pl.yml
Weblate replaces single quotes in this string with double quotes, breaking the html. I'm removing quotes altogether to avoid the issue.
*note that usually language files shouldn't be edited from Github. I'm doing it here because the images will look broken otherwise*
=> remove double quote to avoid breaking img in press kit

.github/workflows/hashes.yaml, _data/downloads.yml, downloads/index.md
In preperation for v0.18.3.2 adding support for RISC-V.
=> downloads: add Linux RISC-V link

_data/downloads.yml, downloads/hashes.txt, downloads/index.md
New hashes for release CLI&GUI, v0.18.3.2
Add new hash for linuxriscv64
Rename links risc -> riscv
=> New release CLI&GUI, v0.18.3.2

_i18n/en.yml, resources/roadmap/index.md
Looking for suggestions on what to add in the "2023" achievements tab
Closes #2204
=> update roadmap page for 2023

_i18n/ar/resources/moneropedia/unlocktime.md, _i18n/ar/resources/moneropedia/weblate/unlocktime.po, _i18n/de/resources/moneropedia/unlocktime.md, _i18n/de/resources/moneropedia/weblate/unlocktime.po, _i18n/en/resources/moneropedia/weblate/unlocktime.pot, _i18n/es/resources/moneropedia/unlocktime.md, _i18n/es/resources/moneropedia/weblate/unlocktime.po, _i18n/fr/resources/moneropedia/unlocktime.md, _i18n/fr/resources/moneropedia/weblate/unlocktime.po, _i18n/it/resources/moneropedia/unlocktime.md, _i18n/it/resources/moneropedia/weblate/unlocktime.po, _i18n/nb-no/resources/moneropedia/unlocktime.md, _i18n/nb-no/resources/moneropedia/weblate/unlocktime.po, _i18n/nl/resources/moneropedia/unlocktime.md, _i18n/nl/resources/moneropedia/weblate/unlocktime.po, _i18n/pl/resources/moneropedia/unlocktime.md, _i18n/pl/resources/moneropedia/weblate/unlocktime.po, _i18n/pt-br/resources/moneropedia/unlocktime.md, _i18n/pt-br/resources/moneropedia/weblate/unlocktime.po, _i18n/ru/resources/moneropedia/ring-size.md, _i18n/ru/resources/moneropedia/unlocktime.md, _i18n/ru/resources/moneropedia/weblate/ring-size.po, _i18n/ru/resources/moneropedia/weblate/unlocktime.po, _i18n/tr/resources/moneropedia/unlocktime.md, _i18n/tr/resources/moneropedia/weblate/unlocktime.po, _i18n/zh-cn/resources/moneropedia/unlocktime.md, _i18n/zh-cn/resources/moneropedia/weblate/unlocktime.po, _i18n/zh-tw/resources/moneropedia/unlocktime.md, _i18n/zh-tw/resources/moneropedia/weblate/unlocktime.po
To adapt all languages after https://github.com/monero-project/monero-site/pull/2198 was merged
=> update i18n moneropedia entry unlocktime

_i18n/en.yml
=> press-kit: fix "used" typo

_i18n/en.yml, downloads/index.md
closes #2239, replaces / closes #2213
=> downloads: add trezor safe 3

get-started/mining/index.md
=> Update get-started/mining/index.md link

_i18n/en.yml
squashed version of #2280 with same author
=> _i18n/en.yml: add rct moneropedia link

community/merchants/index.md
=> Add MajesticBank to swappers

community/merchants/index.md
=> merchants: add tradeogre

_i18n/en.yml
This is meant to give some stricter guidelines on what should be listed on the "mobile and light wallets" section (like the wallets being non-custodial). Personally, i would have added open source as well as a requirement, but i wouldn't agree with removing MyMonero from the list. I would be ok with a way for visually displaying if the wallets listed are fully foss or not).
=> downloads: clarify mobile and light wallets section

README.md, _data/chats.yml, _i18n/el.yml, _i18n/en.yml, _i18n/es.yml, _i18n/fr.yml, _i18n/ru.yml, community/hangouts/index.md, community/workgroups/index.md
`#` points to the rooms alias, but should be `%23` for it to be a valid URI. however, `!` does not work for some reason, i see failed to join room.
To confirm , enter https://matrix.to/#/#monero:monero.social @ https://0mg.github.io/tools/uri/
=> uri: fix invalid uris + readme edit

resources/developer-guides/wallet-rpc.md
=> devguides: fix typo

_i18n/en.yml, downloads/index.md
=> Downloads index/_i18n/en.yml: remove pay for rpc

_i18n/en.yml, resources/tools/index.md
=> remove cryptofacile

get-started/faq/index.md
closes #2206 
The full size mp4 can be found at @ https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/412#note_25078 , vostoemisio supplied the webm version promptly.
lets get some feedback on the video
=> faq: add randomx animated video

_i18n/en.yml, press-kit/index.md
=> press-kit: add monero.graphics

legal/index.md
Should we also remove "Password Protected Areas" as it is irrelevant because the forum is now inaccessible?
Also please revise the grammar changes I made.
=> Update Legal, monero compile link and grammar

css/custom.css, get-started/contributing/index.md
make donation addresses selectable with one click (instead of two)
=> contributing: make one click selectable addresses

downloads/index.md
- fix mobile view
- add desktop support icons
=> downloads: fix stack wallet

downloads/index.md
=> fix ledger link

get-started/mining/index.md
=> getting-started: mining; remove pools.xmr.wiki

resources/developer-guides/daemon-rpc.md, resources/developer-guides/index.md, resources/developer-guides/wallet-rpc.md
Alternative to #2376
- Change hyperlinks
- Add deprecation notice to the rpc docs (for people who have bookmarks)
=> rpc: depreciation warning

resources/developer-guides/daemon-rpc.md, resources/developer-guides/wallet-rpc.md
https://deploy-preview-2392--barolo-time-757cf9.netlify.app/resources/developer-guides/wallet-rpc.html
https://deploy-preview-2392--barolo-time-757cf9.netlify.app/resources/developer-guides/daemon-rpc.html
https://deploy-preview-2392--barolo-time-757cf9.netlify.app/resources/developer-guides
=> dev-guides: deprecated_url for daemon/wallet rpc

_i18n/en.yml, resources/tools/index.md
=> Remove KryptoCheck.de

_i18n/en.yml, get-started/contributing/index.md, resources/user-guides/index.md
* Remove xmrguide
* Fix the broken I2P guide text & link
closes #2396
=> remove xmrguide and fix broken text

_i18n/en.yml, _i18n/en/resources/user-guides/importing_blockchain.md, downloads/index.md, get-started/faq/index.md
current version on getmonero as of making this issue: (its has been updated since)
>71697681675 Feb 23  2023 blockchain.new
benefits of this PR:
- reduction in resources for getmoneros server (bandwidth/disk usage)
- make people verify their own blockchain / decentralisation / reduced liability for getmonero , or any other buzzwords that may support this  
- often times users run into problems when beginning with an imported blockchain or it simply prolonged their suffering before seeking help
=> downloads/faq: remove blockchain.raw

downloads/index.md
=> downloads: fix monerocom wallet name and logo for mobile

_i18n/en.yml
todo: add @nahuhh and @HardenedSteel as authors
=> faq: update the outdated content

_posts/2025-03-10-ospead-optimal-ring-signature-research.md
Suggested at [February 26, 2025 MRL meeting](https://github.com/monero-project/meta/issues/1162).
=> Create "OSPEAD - Optimal Ring Signature Research" blog post

_i18n/en.yml, get-started/faq/index.md
https://deploy-preview-2447--barolo-time-757cf9.netlify.app/get-started/faq/#videos
=> faq: add FCMP video

_i18n/en.yml, downloads/index.md
=> Downloads: add trezor safe 5 hww

downloads/index.md
supported from v4.22 https://cakelabs.com/news/ledger-monero-cakewallet/
=> Downloads: Monero.com wallet supports ledger

downloads/index.md
removed in #2241 but mobile view tab was left
=> Downloads: remove blockchain tab from mobile view

_i18n/en.yml, downloads/index.md
channels such as `#monero-dev` and `#monero-gui` aren't for user support.
linked to hangouts page
=> downloads: link to hangouts for help/support

_i18n/en.yml, get-started/faq/index.md, resources/roadmap/index.md
=> i18n roadmap faq: add hyphen to fcmp / remove duplicate keys

.github/workflows/auto-updater.yaml
workflow run here https://github.com/plowsof/monero-site/actions/runs/14738855728
=> ci: verify previous tag detects new update

README.md, _includes/footer.html
Resolves: #2499 
Resolves: #2488
revert if/when weblate comes back online
=> i18n: remove weblate from footer + add notice in README
